Repository mono/monodevelop, pull requests merged in 2018-03, with the labels that each got.

#3616 Editorconfig
  NuGet.config
  main/src/addins/CSharpBinding/CSharpBinding.addin.xml
  main/src/addins/CSharpBinding/CSharpBinding.csproj
  main/src/addins/CSharpBinding/MonoDevelop.CSharp.CodeGeneration/CodeGenerationOptions.cs
  main/src/addins/CSharpBinding/MonoDevelop.CSharp.Formatting/CSharpFormatter.cs
  main/src/addins/CSharpBinding/MonoDevelop.CSharp.Formatting/CSharpFormattingPolicyPanelWidget.cs
  main/src/addins/CSharpBinding/MonoDevelop.CSharp.Formatting/CSharpFormattingProfileDialog.cs
  main/src/addins/CSharpBinding/MonoDevelop.CSharp.Formatting/CSharpTextEditorIndentation.cs
  main/src/addins/CSharpBinding/MonoDevelop.CSharp.Formatting/OnTheFlyFormatter.cs
  main/src/addins/CSharpBinding/MonoDevelop.CSharp.OptionProvider/CSharpDocumentOptionsProvider.cs
  main/src/addins/CSharpBinding/MonoDevelop.CSharp.OptionProvider/OptionProviderFactory.cs
  main/src/addins/CSharpBinding/MonoDevelop.CSharp.Refactoring/CodeGenerationService.cs
  main/src/addins/CSharpBinding/MonoDevelop.CSharp.Resolver/HelperMethods.cs
  main/src/addins/MonoDevelop.GtkCore/MonoDevelop.GtkCore/WidgetFileDescriptionTemplate.cs
  main/src/addins/MonoDevelop.Packaging/MonoDevelop.Packaging/AddPlatformImplementationViewModel.cs
  main/src/core/MonoDevelop.Core/MonoDevelop.Core.csproj
  main/src/core/MonoDevelop.Core/packages.config
  main/src/core/MonoDevelop.Ide/ExtensionModel/MonoDevelop.Ide.addin.xml
  main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Editor/DefaultSourceEditorOptions.cs
  main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Editor/EditorConfigService.cs
  main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Editor/TextEditorViewContent.cs
  main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Content/TextStylePolicy.cs
  main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Projects/NewFileDialog.cs
  main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Templates/DirectoryTemplate.cs
  main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Templates/FileDescriptionTemplate.cs
  main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Templates/FileTemplate.cs
  main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Templates/FileTemplateReference.cs
  main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Templates/ProjectDescriptor.cs
  main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Templates/PropertyDescriptionTemplate.cs
  main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Templates/ResourceFileDescriptionTemplate.cs
  main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Templates/SingleFileDescriptionTemplate.cs
  main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Templates/TextFileDescriptionTemplate.cs
  main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.TypeSystem/MonoDevelopWorkspace.cs
  main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.csproj
  main/src/core/MonoDevelop.Ide/packages.config
  main/tests/Ide.Tests/MonoDevelop.Ide.Editor/EditorConfigTests.cs
  main/tests/Ide.Tests/MonoDevelop.Ide.Tests.csproj
  main/tests/MonoDevelop.CSharpBinding.Tests/MonoDevelop.CSharpBinding/CSharpTextEditorIndentationTests.cs
  main/tests/MonoDevelop.CSharpBinding.Tests/MonoDevelop.CSharpBinding/OnTheFlyFormatterTests.cs
Labels: do-not-merge

#4107 D15-6 fix 577640
  main/external/fsharpbinding/MonoDevelop.FSharpBinding/HighlightUnusedCode.fs
Labels: Area: F#

#4112 [F#] Fix exception in Android xaml previewer
  main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.TypeSystem/TypeSystemService_WorkspaceHandling.cs
Labels: Area: F#

#4098 [Ide] Fix editor tooltip theme fitting
  main/src/addins/CSharpBinding/MonoDevelop.CSharp/SignatureMarkupCreator.cs
  main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.CodeCompletion/RoslynCompletionData.cs
  main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.CodeCompletion/SignatureHelpParameterHintingData.cs
  main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Editor.Highlighting/SyntaxHighlightingService.cs
Labels: high-priority

#4140 [529478][Ide] Fix Light search result highlight color
  main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Editor.Highlighting/themes/LightStyle.json
Labels: do-not-merge

#4069 [15.7][61249][Mac] Trigger global search when initiated from the editor
  main/src/addins/MacPlatform/MainToolbar/MainToolbar.cs
Labels: qa-pending

#4183 Fix 578232 on 15.6 by bumping Mono.Cecil version
  main/src/core/MonoDevelop.Core/MonoDevelop.Core.csproj
  main/src/core/MonoDevelop.Core/packages.config
Labels: qa-pending

#4203 [TextEditor] Always fetch the preedit string
  main/src/addins/MonoDevelop.SourceEditor2/Mono.TextEditor/Gui/TextArea.cs
Labels: Area: Text Editor

#4204 [15.7] [TextEditor] Always fetch the preedit string
  main/src/addins/MonoDevelop.SourceEditor2/Mono.TextEditor/Gui/TextArea.cs
Labels: Area: Text Editor

#4193 [15.6] Extreme drop in editor performance after update to version
  main/src/addins/MonoDevelop.Refactoring/MonoDevelop.CodeIssues/CodeDiagnosticRunner.cs
  main/src/addins/MonoDevelop.SourceEditor2/MonoDevelop.SourceEditor/SourceEditorView.cs
  main/src/core/Mono.TextEditor.Shared/Mono.TextEditor.Utils/CompressingTreeList.cs
  main/src/core/Mono.TextEditor.Shared/Mono.TextEditor/Document/DiffTracker.cs
  main/src/core/MonoDevelop.TextEditor.Tests/Mono.TextEditor.Tests/DiffTrackerTests.cs
  main/src/core/MonoDevelop.TextEditor.Tests/MonoDevelop.TextEditor.Tests.csproj
Labels: qa-pending

#4184 [15.6] Fixes VSTS 581661: [Feedback] /* */ Comments slow or non responsive
  main/src/addins/MonoDevelop.SourceEditor2/Mono.TextEditor/Gui/TextViewMargin.cs
  main/src/core/Mono.TextEditor.Shared/Mono.TextEditor/Document/DocumentUpdateRequest.cs
  main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Editor.Highlighting/ISyntaxHighlighting.cs
  main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Editor.Highlighting/SyntaxHighlighting.cs
Labels: qa-pending

#4170 [15.7] [Editor] Commit and clear preedit string when changing lines
  main/src/addins/MonoDevelop.SourceEditor2/Mono.TextEditor/Gui/MonoTextEditor.cs
  main/src/addins/MonoDevelop.SourceEditor2/Mono.TextEditor/Gui/TextArea.cs
  main/src/addins/MonoDevelop.SourceEditor2/Mono.TextEditor/Gui/TextViewMargin.cs
Labels: Area: Text Editor
