Repository mono/monodevelop, pull requests merged in 2018-07, with the labels that each got.

#5240 Properties and measures 7.6
  main/src/addins/CSharpBinding/MonoDevelop.CSharp.Features/GotoDefinition/GotoDefinitionService.cs
  main/src/addins/CSharpBinding/MonoDevelop.CSharp.Navigation/Counters.cs
  main/src/addins/CSharpBinding/MonoDevelop.CSharp.Navigation/FindDerivedSymbolsHandler.cs
  main/src/addins/CSharpBinding/MonoDevelop.CSharp.Navigation/FindExtensionMethodsHandler.cs
  main/src/addins/CSharpBinding/MonoDevelop.CSharp.Navigation/FindImplementingMembersHandler.cs
  main/src/addins/CSharpBinding/MonoDevelop.CSharp.Navigation/FindMemberOverloadsHandler.cs
  main/src/addins/CSharpBinding/MonoDevelop.CSharp.Refactoring/FindReferencesHandler.cs
  main/src/addins/CSharpBinding/MonoDevelop.CSharp.Refactoring/GotoBaseDeclarationHandler.cs
  main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement.Tests/MonoDevelop.PackageManagement.Tests/BackgroundPackageActionRunnerTests.cs
  main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement.Tests/MonoDevelop.PackageManagement.Tests/TestableInstrumentationService.cs
  main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement/PackageManagementInstrumentationService.cs
  main/src/addins/MonoDevelop.Refactoring/MonoDevelop.Refactoring/RefactoringService.cs
  main/src/addins/MonoDevelop.SourceEditor2/Mono.TextEditor/Gui/TextEditorKeyPressTimings.cs
  main/src/addins/MonoDevelop.SourceEditor2/MonoDevelop.SourceEditor/Counters.cs
  main/src/addins/VersionControl/MonoDevelop.VersionControl/MonoDevelop.VersionControl/Repository.cs
  main/src/core/MonoDevelop.Core/MonoDevelop.Core.Instrumentation/Counter.cs
  main/src/core/MonoDevelop.Core/MonoDevelop.Core.Instrumentation/TimeCounter.cs
  main/src/core/MonoDevelop.Core/MonoDevelop.Core.Instrumentation/TimerCounter.cs
  main/src/core/MonoDevelop.Core/MonoDevelop.Projects/Project.cs
  main/src/core/MonoDevelop.Core/MonoDevelop.Projects/ProjectService.cs
  main/src/core/MonoDevelop.Core/MonoDevelop.Projects/SolutionItem.cs
  main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Editor.Extension/CompletionStatistics.cs
  main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui/Workbench.cs
  main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Templates/MicrosoftTemplateEngineProjectTemplatingProvider.cs
  main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Templates/ProjectTemplate.cs
  main/src/core/MonoDevelop.Ide/MonoDevelop.Ide/Ide.cs
  main/src/core/MonoDevelop.Ide/MonoDevelop.Ide/IdeStartup.cs
  main/src/core/MonoDevelop.Ide/MonoDevelop.Ide/RootWorkspace.cs
  main/src/core/MonoDevelop.Ide/MonoDevelop.Ide/Services.cs
  main/tests/MonoDevelop.Core.Tests/MonoDevelop.Core/InstrumentationTests.cs
Labels: do-not-merge

#5379 [Core] Make Disconnected event handler actually waited for
  main/src/core/MonoDevelop.Core/MonoDevelop.Projects.MSBuild/RemoteBuildEngine.cs
  main/src/core/MonoDevelop.Projects.Formats.MSBuild/MonoDevelop.Projects.MSBuild/BuildEngine.Shared.cs
Labels: verified

#5378 [DotNetCore] Fix project not restored on target framework being changed
  main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore.Gui/DotNetCoreRuntimeOptionsPanelWidget.cs
  main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore/DotNetCoreProjectExtension.cs
  main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement.Commands/RestorePackagesInProjectHandler.cs
  main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement.Tests/MonoDevelop.PackageManagement.Tests/ProjectTargetFrameworkMonitorTests.cs
  main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement/PackageManagementServices.cs
  main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement/ProjectTargetFrameworkChangedEventArgs.cs
  main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement/ProjectTargetFrameworkMonitor.cs
  main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement/RestoreNuGetPackagesInNuGetIntegratedProject.cs
Labels: verified

#5196 [StructuredOutput] Fixes rounding rendering duration time
  main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.BuildOutputView/BuildOutputNode.cs
  main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.BuildOutputView/BuildOutputTreeCellView.cs
Labels: Area: Structured Build Output

#5428 [StructuredOutput] Fixes select last character in node title
  main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.BuildOutputView/BuildOutputTreeCellView.cs
  main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.BuildOutputView/BuildOutputWidget.cs
Labels: Area: Structured Build Output

#5437 [TODO] Fix todo comments not showing up in some cases
  main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.TypeSystem/Tag.cs
Labels: verified

#5419 [StructuredOutput] Adds overall time to the renderer
  main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.BuildOutputView/BuildOutput.cs
  main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.BuildOutputView/BuildOutputTreeCellView.cs
Labels: Area: Structured Build Output
