Repository mono/monodevelop, pull requests merged in 2018-09, with the labels that each got.

#5906 Fix VSTS 669803: using vstool with Razor
  main/src/core/MonoDevelop.Core/MonoDevelop.Core/Runtime.cs
  main/src/tools/mdtool/src/mdtool.cs
Labels: do-not-merge

#5975 [MacPlatform] Fix credential provider dialog tabbing and focus
  main/src/addins/MacPlatform/MacProxyCredentialProvider.cs
Labels: verified

#5943 [Ide] Dark theme support fixes for Mojave
  main/src/addins/MacPlatform/Dialogs/MacAlertDialogHandler.cs
  main/src/addins/MacPlatform/Dialogs/MacCommonFileDialogHandler.cs
  main/src/addins/MacPlatform/MacPlatform.cs
  main/src/addins/MacPlatform/MainToolbar/RunButton.cs
  main/src/addins/MacPlatform/MainToolbar/StatusBar.cs
  main/src/core/MonoDevelop.Ide/MonoDevelop.Components/IdeTheme.cs
Labels: qa-pending

#5981 [release-7.6] [Ide] Dark theme support fixes for Mojave
  main/src/addins/MacPlatform/Dialogs/MacAlertDialogHandler.cs
  main/src/addins/MacPlatform/Dialogs/MacCommonFileDialogHandler.cs
  main/src/addins/MacPlatform/MacPlatform.cs
  main/src/addins/MacPlatform/MainToolbar/RunButton.cs
  main/src/addins/MacPlatform/MainToolbar/StatusBar.cs
  main/src/core/MonoDevelop.Ide/MonoDevelop.Components/IdeTheme.cs
Labels: do-not-merge

#6126 [release-7.7] [DotNetCore] Add support for .NET Core 2.2
  main/src/addins/MonoDevelop.AspNetCore/Properties/MonoDevelop.AspNetCore.addin.xml
  main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore.Templating/DotNetCoreProjectTemplateStringTagProvider.cs
  main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore.Templating/DotNetCoreProjectTemplateWizard.cs
  main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore.Templating/DotNetCoreProjectTemplateWizardPage.cs
  main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore.Tests/MonoDevelop.DotNetCore.Tests/DotNetCoreProjectSupportedTargetFrameworksTests.cs
  main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore.Tests/MonoDevelop.DotNetCore.Tests/DotNetCoreProjectTemplateStringTagProviderTests.cs
  main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore.Tests/MonoDevelop.DotNetCore.Tests/DotNetCoreProjectTemplateTests.cs
  main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore.Tests/MonoDevelop.DotNetCore.Tests/DotNetCoreProjectTemplateWizardTests.cs
  main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore/DotNetCoreNotInstalledDialog.cs
  main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore/DotNetCoreProjectExtension.cs
  main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore/DotNetCoreProjectSupportedTargetFrameworks.cs
  main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore/DotNetCoreSdkInstalledCondition.cs
  main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore/TargetFrameworkExtensions.cs
  main/src/addins/MonoDevelop.DotNetCore/Properties/MonoDevelop.DotNetCore.addin.xml
Labels: verified

#6122 Fixes issue #6104 Invalid URI exception on opening file in root
  main/src/core/MonoDevelop.Core/MonoDevelop.Projects/FileWatcherService.cs
  main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Editor/EditorConfigService.cs
Labels: verified

#6124 [release-7.7] Fixes issue #6089 StackOverflow on running unit tests
  main/src/core/MonoDevelop.Core/MonoDevelop.Projects/SolutionFolder.cs
Labels: verified
