Repository mono/monodevelop, pull requests merged in 2018-04, with the labels that each got.

#4202 [Editor] Commit and clear preedit string when changing lines
  main/src/addins/MonoDevelop.SourceEditor2/Mono.TextEditor/Gui/MonoTextEditor.cs
  main/src/addins/MonoDevelop.SourceEditor2/Mono.TextEditor/Gui/TextArea.cs
  main/src/addins/MonoDevelop.SourceEditor2/Mono.TextEditor/Gui/TextViewMargin.cs
Labels: Area: Text Editor

#4412 Fixes issue #4346 Text editor - curly brace problems
  main/src/addins/MonoDevelop.SourceEditor2/Mono.TextEditor/Gui/TextViewMargin.cs
Labels: qa-pending

#4543 [d15-7][Core] Support facade assemblies from a custom location
  main/src/core/MonoDevelop.Core/MonoDevelop.Projects/DotNetProject.cs
  main/src/core/MonoDevelop.Core/MonoDevelop.Projects/DotNetProjectExtension.cs
  version-checks
Labels: qa-pending

#4671 Fixes issue #4670 [Linux] Monodevelop fsharpbinding doesn't compile
  main/external/fsharpbinding/.paket/paket.bootstrapper.exe
Labels: Area: F#, linux

#4682 [d15-7] Fixes VSTS 605909: IDE crash on attempt to override something in the
  main/src/addins/CSharpBinding/MonoDevelop.CSharp.Completion/CompletionProvider/ProtocolMemberCompletionProvider.cs
Labels: qa-pending

#4669 [d15-7] Fixes issue #4667 [TextEditor] SmartTag marker position wrong.
  main/src/addins/MonoDevelop.SourceEditor2/MonoDevelop.SourceEditor/TextMarker/SmartTagMarker.cs
Labels: qa-pending
