Repository mono/monodevelop, pull requests merged in 2018-08, with the labels that each got.

#5473 [Ide] Don't show welcome page when opening a specific item
  main/src/core/MonoDevelop.Ide/MonoDevelop.Ide/Ide.cs
  main/src/core/MonoDevelop.Ide/MonoDevelop.Ide/IdeStartup.cs
Labels: verified

#4683 Fix 593840: MetadataReferenceCache implementation does IO on the UI thread
  main/src/addins/AspNet/WebForms/WebFormsTypeContext.cs
  main/src/addins/CSharpBinding/MonoDevelop.CSharp.Project/CSharpCompilerParameters.cs
  main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/BreakpointPropertiesDialog.cs
  main/src/core/MonoDevelop.Core/MonoDevelop.Core/Runtime.cs
  main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.TypeSystem/MetadataReferenceCache.cs
  main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.TypeSystem/MonoDevelopMetadataReference.Snapshot.cs
  main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.TypeSystem/MonoDevelopMetadataReference.cs
  main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.TypeSystem/MonoDevelopMetadataReferenceManager.MetadataCache.cs
  main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.TypeSystem/MonoDevelopMetadataReferenceManager.MetadataReferenceCache.cs
  main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.TypeSystem/MonoDevelopMetadataReferenceManager.RecoverableMetadataValueSource.cs
  main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.TypeSystem/MonoDevelopMetadataReferenceManager.cs
  main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.TypeSystem/MonoDevelopMetadataServiceFactory.cs
  main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.TypeSystem/MonoDevelopWorkspace.cs
  main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.TypeSystem/TypeSystemService_WorkspaceHandling.cs
  main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.csproj
  main/src/core/MonoDevelop.Ide/MonoDevelop.Ide/RootWorkspace.cs
  main/tests/Ide.Tests/MonoDevelop.Ide.Tests.csproj
  main/tests/Ide.Tests/MonoDevelop.Ide.TypeSystem/MonoDevelopMetadataReferenceManager.MetadataCache.cs
  main/tests/Ide.Tests/MonoDevelop.Ide.TypeSystem/MonoDevelopMetadataReferenceManager.MetadataReferenceCache.cs
  main/tests/Ide.Tests/MonoDevelop.Ide.TypeSystem/MonoDevelopMetadataReferenceManager.MetadataReferenceCacheTests.cs
  main/tests/Ide.Tests/MonoDevelop.Ide.TypeSystem/MonoDevelopMetadataReferenceManager.RecoverableMetadataValueSource.cs
  main/tests/Ide.Tests/MonoDevelop.Ide.TypeSystem/MonoDevelopMetadataReferenceManager.cs
  main/tests/Ide.Tests/MonoDevelop.Ide.TypeSystem/MonoDevelopMetadataReferenceManagerTests.cs
  main/tests/Ide.Tests/MonoDevelop.Ide.TypeSystem/MonoDevelopMetadataServiceFactory.cs
  main/tests/MonoDevelop.Core.Tests/MonoDevelop.Core.Tests.csproj
Labels: verified

#5461 [StructuredOutput] Changes expander icon to match with TreeView expander behaviour
  main/src/core/MonoDevelop.Ide/ExtensionModel/StockIcons.addin.xml
  main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.BuildOutputView/BuildOutputNode.cs
  main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.BuildOutputView/BuildOutputTreeCellView.cs
  main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.csproj
  main/src/core/MonoDevelop.Ide/icons/tree-chevron-closed.png
  main/src/core/MonoDevelop.Ide/icons/tree-chevron-closed@2x.png
  main/src/core/MonoDevelop.Ide/icons/tree-chevron-closed~dark.png
  main/src/core/MonoDevelop.Ide/icons/tree-chevron-closed~dark@2x.png
  main/src/core/MonoDevelop.Ide/icons/tree-chevron-open.png
  main/src/core/MonoDevelop.Ide/icons/tree-chevron-open@2x.png
  main/src/core/MonoDevelop.Ide/icons/tree-chevron-open~dark.png
  main/src/core/MonoDevelop.Ide/icons/tree-chevron-open~dark@2x.png
Labels: Area: Structured Build Output, verified

#5614 7.6 fix 595915
  main/src/core/MonoDevelop.Ide/ExtensionModel/StockIcons.addin.xml
  main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.BuildOutputView/BuildOutputNode.cs
  main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.BuildOutputView/BuildOutputTreeCellView.cs
  main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.csproj
  main/src/core/MonoDevelop.Ide/icons/tree-chevron-closed.png
  main/src/core/MonoDevelop.Ide/icons/tree-chevron-closed@2x.png
  main/src/core/MonoDevelop.Ide/icons/tree-chevron-closed~dark.png
  main/src/core/MonoDevelop.Ide/icons/tree-chevron-closed~dark@2x.png
  main/src/core/MonoDevelop.Ide/icons/tree-chevron-open.png
  main/src/core/MonoDevelop.Ide/icons/tree-chevron-open@2x.png
  main/src/core/MonoDevelop.Ide/icons/tree-chevron-open~dark.png
  main/src/core/MonoDevelop.Ide/icons/tree-chevron-open~dark@2x.png
Labels: verified

#5582 [7.6] Remove preview label
  version.config
Labels: MUST SHIP

#5639 [Ide] Add "log verbosity" setting back
  main/src/core/MonoDevelop.Ide/Gui/MonoDevelop.Ide.Gui.OptionPanels.BuildPanelWidget.cs
  main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.OptionPanels/BuildPanel.cs
Labels: verified

#5736 Fixes VSTS Bug 650534: [Feedback] High CPU usage viewing "Search in
  main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.FindInFiles/SearchResult.cs
  main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.FindInFiles/SearchResultWidget.cs
Labels: verified

#5111 Fixes VSTS Bug 631500: [Feedback] EditorConfig doesn't work for VS for Mac using .NET Core Rules
  main/src/addins/CSharpBinding/CSharpBinding.addin.xml
  main/src/addins/CSharpBinding/CSharpBinding.csproj
  main/src/addins/CSharpBinding/MonoDevelop.CSharp.OptionProvider/CSharpDocumentOptionsProvider.cs
  main/src/addins/CSharpBinding/MonoDevelop.CSharp.OptionProvider/StyleViewModel.cs
  main/src/addins/CSharpBinding/MonoDevelop.CSharp.Project/CSharpCompilerParameters.cs
  main/src/addins/MonoDevelop.Refactoring/Gui/MonoDevelop.CodeIssues.CodeIssuePanelWidget.cs
  main/src/addins/MonoDevelop.Refactoring/MonoDevelop.AnalysisCore/AnalysisCommands.cs
  main/src/addins/MonoDevelop.Refactoring/MonoDevelop.CodeActions/CodeActionPanelWidget.cs
  main/src/addins/MonoDevelop.Refactoring/MonoDevelop.CodeActions/CodeFixMenuService.cs
  main/src/addins/MonoDevelop.Refactoring/MonoDevelop.CodeIssues/CodeDiagnosticDescriptor.cs
  main/src/addins/MonoDevelop.Refactoring/MonoDevelop.CodeIssues/CodeDiagnosticRunner.cs
  main/src/addins/MonoDevelop.Refactoring/MonoDevelop.CodeIssues/CodeIssuePanelWidget.cs
  main/src/addins/MonoDevelop.Refactoring/MonoDevelop.CodeIssues/CodeRulePanel.cs
  main/src/addins/MonoDevelop.Refactoring/MonoDevelop.Refactoring.Options/AbstractCheckBoxViewModel.cs
  main/src/addins/MonoDevelop.Refactoring/MonoDevelop.Refactoring.Options/AbstractNotifyPropertyChanged.cs
  main/src/addins/MonoDevelop.Refactoring/MonoDevelop.Refactoring.Options/AbstractOptionPreviewViewModel.cs
  main/src/addins/MonoDevelop.Refactoring/MonoDevelop.Refactoring.Options/AbstractRadioButtonViewModel.cs
  main/src/addins/MonoDevelop.Refactoring/MonoDevelop.Refactoring.Options/CheckBoxOptionViewModel.cs
  main/src/addins/MonoDevelop.Refactoring/MonoDevelop.Refactoring.Options/CheckBoxWithComboOptionViewModel.cs
  main/src/addins/MonoDevelop.Refactoring/MonoDevelop.Refactoring.Options/NotificationOptionViewModel.cs
  main/src/addins/MonoDevelop.Refactoring/MonoDevelop.Refactoring.Options/OptionBinding.cs
  main/src/addins/MonoDevelop.Refactoring/MonoDevelop.Refactoring.Options/RadioButtonViewModel.cs
  main/src/addins/MonoDevelop.Refactoring/MonoDevelop.Refactoring.Options/Style/AbstractCodeStyleOptionViewModel.cs
  main/src/addins/MonoDevelop.Refactoring/MonoDevelop.Refactoring.Options/Style/BooleanCodeStyleOptionViewModel.cs
  main/src/addins/MonoDevelop.Refactoring/MonoDevelop.Refactoring.Options/Style/CodeStylePreference.cs
  main/src/addins/MonoDevelop.Refactoring/MonoDevelop.Refactoring.Options/Style/EnumCodeStyleOptionViewModel.cs
  main/src/addins/MonoDevelop.Refactoring/MonoDevelop.Refactoring.Options/UI/GridOptionPreviewControl.cs
  main/src/addins/MonoDevelop.Refactoring/MonoDevelop.Refactoring.Options/Util.cs
  main/src/addins/MonoDevelop.Refactoring/MonoDevelop.Refactoring.Rename/SymbolRenamedCodeActionOperationFactoryWorkspaceService.cs
  main/src/addins/MonoDevelop.Refactoring/MonoDevelop.Refactoring.addin.xml
  main/src/addins/MonoDevelop.Refactoring/MonoDevelop.Refactoring.csproj
  main/src/addins/MonoDevelop.SourceEditor2/MonoDevelop.SourceEditor/StyledSourceEditorOptions.cs
  main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Editor/CustomEditorOptions.cs
  main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Editor/DefaultSourceEditorOptions.cs
  main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Editor/ITextEditorOptions.cs
  main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.RoslynServices.Options/MonoDevelopGlobalOptionPersister.cs
  main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.TypeSystem/MonoDevelopRuleSetManager.cs
  main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.TypeSystem/MonoDevelopWorkspace.cs
  main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.csproj
Labels: qa-pending
