Repository mono/monodevelop, pull requests merged in 2018-02, with the labels that each got.

#3808 Fix VSTS #527500 D15 6 fixall
  main/src/addins/MonoDevelop.Refactoring/MonoDevelop.CodeActions/CodeFixMenuService.cs
  main/src/addins/MonoDevelop.Refactoring/MonoDevelop.CodeIssues/CodeDiagnosticRunner.cs
  main/src/addins/MonoDevelop.Refactoring/MonoDevelop.Refactoring.addin.xml
Labels: qa-pending

#3792 [d15-6][Git] Fix progress reporting on clone
  main/src/addins/VersionControl/MonoDevelop.VersionControl.Git.Tests/BaseGitRepositoryTests.cs
  main/src/addins/VersionControl/MonoDevelop.VersionControl.Git/MonoDevelop.VersionControl.Git/GitRepository.cs
  main/src/addins/VersionControl/MonoDevelop.VersionControl/MonoDevelop.VersionControl/CheckoutCommand.cs
  main/src/addins/VersionControl/MonoDevelop.VersionControl/MonoDevelop.VersionControl/VersionControlTask.cs
  main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.ProgressMonitoring/BaseProgressMonitor.cs
  main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.ProgressMonitoring/MessageDialogProgressMonitor.cs
Labels: qa-pending

#3897 [F#] Some cleanup and notes
  main/external/fsharpbinding/MonoDevelop.FSharpBinding/FSharpBraceMatcher.fs
  main/external/fsharpbinding/MonoDevelop.FSharpBinding/FSharpDebuggerExpressionResolver.fs
  main/external/fsharpbinding/MonoDevelop.FSharpBinding/FSharpHighlightUsagesExtension.fs
  main/external/fsharpbinding/MonoDevelop.FSharpBinding/FSharpNavigationTextEditorExtension.fs
  main/external/fsharpbinding/MonoDevelop.FSharpBinding/FSharpParsedDocument.fs
  main/external/fsharpbinding/MonoDevelop.FSharpBinding/FSharpParser.fs
  main/external/fsharpbinding/MonoDevelop.FSharpBinding/FSharpProject.fs
  main/external/fsharpbinding/MonoDevelop.FSharpBinding/FSharpTextEditorCompletion.fs
  main/external/fsharpbinding/MonoDevelop.FSharpBinding/FSharpTooltipProvider.fs
  main/external/fsharpbinding/MonoDevelop.FSharpBinding/FSharpUnitTestTextEditorExtension.fs
  main/external/fsharpbinding/MonoDevelop.FSharpBinding/ProjectSearchCategory.fs
  main/external/fsharpbinding/MonoDevelop.FSharpBinding/RefactoringOperationsHandler.fs
  main/external/fsharpbinding/MonoDevelop.FSharpBinding/ScriptDebugging.fs
  main/external/fsharpbinding/MonoDevelop.FSharpBinding/Services/Extensions.fs
  main/external/fsharpbinding/MonoDevelop.FSharpBinding/Services/LanguageService.fs
Labels: Area: F#

#3636 [Refactoring] Switch to Roslyn CodeFixService
  main/src/addins/CSharpBinding/MonoDevelop.CSharp.Parser/CSharpParsedDocument.cs
  main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement.Refactoring/PackageCodeDiagnosticProvider.cs
  main/src/addins/MonoDevelop.Refactoring/MonoDevelop.AnalysisCore/AnalysisCommands.cs
  main/src/addins/MonoDevelop.Refactoring/MonoDevelop.AnalysisCore/MonoDevelopWorkspaceDiagnosticAnalyzerProviderService.OptionsTable.cs
  main/src/addins/MonoDevelop.Refactoring/MonoDevelop.AnalysisCore/MonoDevelopWorkspaceDiagnosticAnalyzerProviderService.cs
  main/src/addins/MonoDevelop.Refactoring/MonoDevelop.CodeActions/CodeActionContainer.cs
  main/src/addins/MonoDevelop.Refactoring/MonoDevelop.CodeActions/CodeActionEditorExtension.cs
  main/src/addins/MonoDevelop.Refactoring/MonoDevelop.CodeActions/CodeActionPanelWidget.cs
  main/src/addins/MonoDevelop.Refactoring/MonoDevelop.CodeActions/CodeFixMenuService.cs
  main/src/addins/MonoDevelop.Refactoring/MonoDevelop.CodeActions/CodeRefactoringService.cs
  main/src/addins/MonoDevelop.Refactoring/MonoDevelop.CodeActions/ValidCodeAction.cs
  main/src/addins/MonoDevelop.Refactoring/MonoDevelop.CodeActions/ValidCodeDiagnosticAction.cs
  main/src/addins/MonoDevelop.Refactoring/MonoDevelop.CodeIssues/AnalyzersFromAssembly.cs
  main/src/addins/MonoDevelop.Refactoring/MonoDevelop.CodeIssues/BuiltInCodeDiagnosticProvider.cs
  main/src/addins/MonoDevelop.Refactoring/MonoDevelop.CodeIssues/CodeDiagnosticDescriptor.cs
  main/src/addins/MonoDevelop.Refactoring/MonoDevelop.CodeIssues/CodeDiagnosticFixDescriptor.cs
  main/src/addins/MonoDevelop.Refactoring/MonoDevelop.CodeIssues/CodeDiagnosticProvider.cs
  main/src/addins/MonoDevelop.Refactoring/MonoDevelop.CodeIssues/CodeDiagnosticRunner.cs
  main/src/addins/MonoDevelop.Refactoring/MonoDevelop.CodeIssues/CodeIssuePanelWidget.cs
  main/src/addins/MonoDevelop.Refactoring/MonoDevelop.Refactoring.addin.xml
  main/src/addins/MonoDevelop.Refactoring/MonoDevelop.Refactoring.csproj
  main/src/addins/MonoDevelop.Refactoring/MonoDevelop.Refactoring/AnalyzeWholeSolutionHandler.cs
  main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.TypeSystem/MonoDevelopWorkspace.cs
  main/tests/MonoDevelop.Refactoring.Tests/CodeActionEditorExtensionTests.cs
  main/tests/MonoDevelop.Refactoring.Tests/MonoDevelop.Refactoring.Tests.csproj
  main/tests/MonoDevelop.Refactoring.Tests/ResultsEditorExtensionTests.cs
Labels: qa-pending

#3913 Remove "Preview"
  version.config
Labels: MUST SHIP

#3946 Native Structured Build Output
  main/src/addins/MacPlatform/MacPlatform.cs
  main/src/addins/MonoDevelop.UnitTesting/Services/AbstractUnitTestEditorExtension.cs
  main/src/core/MonoDevelop.Ide/MonoDevelop.Components.Commands/CommandManager.cs
  main/src/core/MonoDevelop.Ide/MonoDevelop.Components/ContextMenu.cs
  main/src/core/MonoDevelop.Ide/MonoDevelop.Components/ContextMenuExtensionsMac.cs
  main/src/core/MonoDevelop.Ide/MonoDevelop.Components/XwtControl.cs
  main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.BuildOutputView/BuildOutputTreeCellView.cs
  main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.BuildOutputView/BuildOutputViewContent.cs
  main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.BuildOutputView/BuildOutputWidget.cs
  main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui/ViewContent.cs
Labels: do-not-merge
