Repository mono/monodevelop, pull requests merged in 2019-08, with the labels that each got.

#7536 [Ide] Adds feature in MonoDevelop to pin opened tabs
  main/src/core/MonoDevelop.Ide/ExtensionModel/Commands.addin.xml
  main/src/core/MonoDevelop.Ide/ExtensionModel/MonoDevelop.Ide.addin.xml
  main/src/core/MonoDevelop.Ide/MonoDevelop.Components.DockNotebook/DockNotebook.cs
  main/src/core/MonoDevelop.Ide/MonoDevelop.Components.DockNotebook/DockNotebookTab.cs
  main/src/core/MonoDevelop.Ide/MonoDevelop.Components.DockNotebook/TabStrip.cs
  main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Commands/FileCommands.cs
  main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Commands/FileTabCommands.cs
  main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui/Workbench.cs
  main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui/WorkbenchMemento.cs
  main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.csproj
  main/src/core/MonoDevelop.Ide/icons/tab-pinned-9.png
  main/src/core/MonoDevelop.Ide/icons/tab-pinned-9@2x.png
  main/src/core/MonoDevelop.Ide/icons/tab-pinned-9~dark.png
  main/src/core/MonoDevelop.Ide/icons/tab-pinned-9~dark@2x.png
  main/src/core/MonoDevelop.Ide/icons/tab-unpinned-9.png
  main/src/core/MonoDevelop.Ide/icons/tab-unpinned-9@2x.png
  main/src/core/MonoDevelop.Ide/icons/tab-unpinned-9~dark.png
  main/src/core/MonoDevelop.Ide/icons/tab-unpinned-9~dark@2x.png
Labels: Area: Shell, verified

#8303 [DotNetCore] Add support for new templates location in 3.0 preview8
  main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore.Templating/DotNetCoreProjectTemplateStringTagProvider.cs
  main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore.Tests/MonoDevelop.DotNetCore.Tests/DotNetCoreProjectTemplateStringTagProviderTests.cs
  main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore/DotNetCoreVersion.cs
Labels: Area: .NET Core

#8301 Fixes VSTS Bug 952599: Version control document views are missing with
  main/src/addins/VersionControl/MonoDevelop.VersionControl/MonoDevelop.VersionControl/DefaultBlameViewHandler.cs
Labels: verified

#8316 Fixes VSTS Bug 948354: Unpinned docked pads appear unexpectedly after a
  main/src/core/MonoDevelop.Ide/MonoDevelop.Components.Docking/DockBarItem.cs
Labels: verified

#8274 [Core] Attempt at fixing method overload resolving for MSBuild
  main/src/core/MonoDevelop.Core/MonoDevelop.Projects.MSBuild/MSBuildEvaluationContext.cs
  main/src/core/MonoDevelop.Core/MonoDevelop.Projects.MSBuild/MSBuildProjectInstance.cs
  main/src/core/MonoDevelop.Core/MonoDevelop.Projects.MSBuild/ProjectEvaluationException.cs
  main/tests/MonoDevelop.Core.Tests/MonoDevelop.Projects/MSBuildProjectTests.cs
  main/tests/test-projects/msbuild-tests/functions.csproj
Labels: verified

#8333 TextEditor: "Use Selection for Find" fixes
  main/src/addins/MonoDevelop.TextEditor/MonoDevelop.TextEditor.Cocoa/Properties/MonoDevelop.TextEditor.Cocoa.addin.xml
  main/src/core/MonoDevelop.Ide/ExtensionModel/Commands.addin.xml
  main/src/core/MonoDevelop.Ide/ExtensionModel/MainMenu.addin.xml
Labels: Area: VS Text Editor

#8329 Add .NET 4.7.2 target moniker, set it to default for templates and update NUnit Library project to use NUnit 3.12.0
  main/src/addins/MonoDevelop.UnitTesting.NUnit/templates/NUnitProject.xpt.xml
  main/src/addins/MonoDevelop.UnitTesting.NUnit/templates/NUnitProjectVBNet.xpt.xml
  main/src/core/MonoDevelop.Core/MonoDevelop.Core.Assemblies/TargetFrameworkMoniker.cs
  main/src/core/MonoDevelop.Core/MonoDevelop.Projects/ProjectService.cs
Labels: Area: NUnit, Area: Unit Testing

#8347 [Project Model] Fix the text color issue in the Exception Caught Window
  main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/Styles.cs
Labels: verified

#8325 Artificially rank the commands from the current add-in higher in Navigate To
  main/src/core/MonoDevelop.Ide/MonoDevelop.Components.Commands/ActionCommand.cs
  main/src/core/MonoDevelop.Ide/MonoDevelop.Components.MainToolbar/CommandSearchCategory.cs
Labels: Area: General

#8332 Bump Roslyn to 3.3.0-beta2-19401-05
  main/external/fsharpbinding/MonoDevelop.FSharpBinding/Services/RoslynHelpers.fs
  main/msbuild/RoslynVersion.props
Labels: Area: Roslyn Integration, Roslyn: Approved for merge, do-not-merge

#8344 Fixes 941510: Reconcile GoToMatchingBraceCommandArgs with GoToBraceCommandArgs
  main/src/addins/MonoDevelop.TextEditor/MonoDevelop.TextEditor/Properties/MonoDevelop.TextEditor.addin.xml
Labels: Area: VS Text Editor

#8311 [Project Model] Shortcut for add new class in C# projects
  main/src/core/MonoDevelop.Ide/ExtensionModel/Commands.addin.xml
  main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Commands/ProjectCommands.cs
  main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Pads.ProjectPad/FolderNodeBuilder.cs
  main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Pads.ProjectPad/ProjectPadContextMenu.addin.xml
  main/src/core/MonoDevelop.Ide/MonoDevelop.Ide/ProjectOperations.cs
Labels: verified

#8321 [CSharp] Enable Preview
  main/src/addins/CSharpBinding/MonoDevelop.CSharp.Project/CompilerOptionsPanelWidget.cs
Labels: verified

#8357 TextEditor: Allow opening C# files with certain custom themes
  main/src/addins/MonoDevelop.TextEditor/MonoDevelop.TextEditor/ThemeToClassification.cs
Labels: Area: VS Text Editor

#8366 Roslyn: Don't disable Roslyn's semantic QuickInfo after known error
  main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.RoslynServices/MonoDevelopExtensionManager.cs
Labels: Area: Roslyn Integration

#8314 [Project Model] Change "Delete" to "Remove" for project context menu
  main/src/core/MonoDevelop.Ide/ExtensionModel/Commands.addin.xml
  main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Pads.ProjectPad/ProjectNodeBuilder.cs
Labels: verified

#8337 [Project Model] Save severity in C# code analysis
  main/src/addins/MonoDevelop.Refactoring/MonoDevelop.Refactoring.Options/UI/GridOptionPreviewControl.cs
Labels: verified

#8379 [DotNetCore] Add custom .NET Core sdk package sources
  main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore.Tests/MonoDevelop.DotNetCore.Tests/DotNetCoreProjectTemplateTests.cs
  main/tests/IdeUnitTests/ProjectTemplateTest.cs
Labels: Area: .NET Core

#8417 [AspNetCore] Switch to HttpClient from TcpClient
  main/src/addins/MonoDevelop.AspNetCore/MonoDevelop.AspNetCore/AspNetCoreExecutionHandler.cs
Labels: Area: .NET Core

#7683 Launch settings fix
  main/src/addins/MonoDevelop.AspNetCore/MonoDevelop.AspNetCore.Tests/MonoDevelop.AspNetCore.Tests/LaunchSettingsTests.cs
  main/src/addins/MonoDevelop.AspNetCore/MonoDevelop.AspNetCore/AspNetCoreExecutionHandler.cs
  main/src/addins/MonoDevelop.AspNetCore/MonoDevelop.AspNetCore/AspNetCoreProjectExtension.cs
  main/src/addins/MonoDevelop.AspNetCore/MonoDevelop.AspNetCore/AspNetCoreRunConfiguration.cs
  main/src/addins/MonoDevelop.AspNetCore/MonoDevelop.AspNetCore/AspNetCoreRunConfigurationEditor.cs
  main/src/addins/MonoDevelop.AspNetCore/MonoDevelop.AspNetCore/ILaunchProfile.cs
  main/src/addins/MonoDevelop.AspNetCore/MonoDevelop.AspNetCore/LaunchProfileData.cs
  main/src/addins/MonoDevelop.AspNetCore/MonoDevelop.AspNetCore/LaunchProfileProvider.cs
  main/src/core/MonoDevelop.Core/MonoDevelop.Projects/Project.cs
  main/src/core/MonoDevelop.Core/MonoDevelop.Projects/ProjectExtension.cs
Labels: Area: .NET Core

#8382 [VersionControl] GenerateDiff is now async.
  main/src/addins/VersionControl/MonoDevelop.VersionControl.Git.Tests/BaseGitRepositoryTests.cs
  main/src/addins/VersionControl/MonoDevelop.VersionControl.Git/MonoDevelop.VersionControl.Git/GitRepository.cs
  main/src/addins/VersionControl/MonoDevelop.VersionControl.Subversion.Tests/RepositoryTests.cs
  main/src/addins/VersionControl/MonoDevelop.VersionControl.Subversion/MonoDevelop.VersionControl.Subversion/SubversionRepository.cs
  main/src/addins/VersionControl/MonoDevelop.VersionControl/MonoDevelop.VersionControl.Views/StatusView.cs
  main/src/addins/VersionControl/MonoDevelop.VersionControl/MonoDevelop.VersionControl/Repository.cs
  main/src/addins/VersionControl/Subversion.Win32.Tests/RepositoryTests.cs
Labels: verified

#8441 CODEOWNERS: Roslyn area cleanups
  CODEOWNERS
Labels: Area: Roslyn Integration, Area: VS Text Editor

#8444 [release-8.3] CODEOWNERS: Roslyn area cleanups
  CODEOWNERS
Labels: Area: Roslyn Integration, Area: VS Text Editor

#8448 Fixes VSTS Bug 967445: Remove background worker in comparison widget.
  main/src/addins/VersionControl/MonoDevelop.VersionControl/MonoDevelop.VersionControl.Views/ComparisonWidget.cs
Labels: verified

#8458 [AspNetCore] Add Worker Service template
  main/src/addins/MonoDevelop.AspNetCore/Properties/MonoDevelop.AspNetCore.addin.xml
  main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore.Tests/MonoDevelop.DotNetCore.Tests/DotNetCoreProjectTemplateTests.cs
Labels: Area: .NET Core

#8426 TextEditor: Mouse processors don't need to deal with ctrl+click anymore
  main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger.VSTextView/Glyphs/BreakpointGlyphMouseProcessor.cs
  main/src/addins/MonoDevelop.TextEditor/MonoDevelop.TextEditor.Cocoa/MdMouseProcessorProvider.cs
Labels: Area: VS Text Editor

#8427 [release-8.3] TextEditor: Mouse processors don't need to deal with ctrl+click anymore
  main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger.VSTextView/Glyphs/BreakpointGlyphMouseProcessor.cs
  main/src/addins/MonoDevelop.TextEditor/MonoDevelop.TextEditor.Cocoa/MdMouseProcessorProvider.cs
Labels: Area: VS Text Editor

#8323 Fixes VSTS 945987: Format document doesn't work from Navigate To when using the new editor
  main/src/core/MonoDevelop.Ide/MonoDevelop.Components.Commands/CommandManager.cs
  main/src/core/MonoDevelop.Ide/MonoDevelop.Components/Control.cs
  main/src/core/MonoDevelop.Ide/MonoDevelop.Components/Window.cs
Labels: Area: VS Text Editor

#7897 [GlobalSearch] Improves current GlobalSearch performance showing results
  main/external/fsharpbinding/MonoDevelop.FSharpBinding/FakeSearchCategory.fs
  main/external/fsharpbinding/MonoDevelop.FSharpBinding/ProjectSearchCategory.fs
  main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement/SearchPackagesSearchCategory.cs
  main/src/core/MonoDevelop.Ide/MonoDevelop.Components.MainToolbar/CommandSearchCategory.cs
  main/src/core/MonoDevelop.Ide/MonoDevelop.Components.MainToolbar/FileSearchCategory.cs
  main/src/core/MonoDevelop.Ide/MonoDevelop.Components.MainToolbar/RoslynSearchCategory.cs
  main/src/core/MonoDevelop.Ide/MonoDevelop.Components.MainToolbar/SearchCategory.cs
  main/src/core/MonoDevelop.Ide/MonoDevelop.Components.MainToolbar/SearchInSolutionSearchCategory.cs
  main/src/core/MonoDevelop.Ide/MonoDevelop.Components.MainToolbar/SearchPopupWindow.cs
Labels: Area: Shell, verified

#8462 [release-8.3] [Windows] Some fixes to assembly references
  main/msbuild/ReferencesVSEditor.Windows.props
  main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui/ViewCommandHandlers.cs
Labels: Area: VS Text Editor

#8466 [release-8.3] [AspNetCore] Add Worker Service template
  main/src/addins/MonoDevelop.AspNetCore/Properties/MonoDevelop.AspNetCore.addin.xml
  main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore.Tests/MonoDevelop.DotNetCore.Tests/DotNetCoreProjectTemplateTests.cs
Labels: Area: .NET Core

#8436 [aspnetcore] Disables User-specific run config for asp.net core projects
  main/src/addins/AspNet/Projects/AspNetAppProjectFlavor.cs
  main/src/addins/MonoDevelop.AspNetCore/MonoDevelop.AspNetCore/AspNetCoreProjectExtension.cs
  main/src/addins/MonoDevelop.AspNetCore/MonoDevelop.AspNetCore/AspNetCoreRunConfiguration.cs
  main/src/core/MonoDevelop.Core/MonoDevelop.Projects/ProjectFeature.cs
  main/src/core/MonoDevelop.Core/MonoDevelop.Projects/ProjectRunConfiguration.cs
  main/src/core/MonoDevelop.Core/MonoDevelop.Projects/SolutionItem.cs
  main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Projects.OptionPanels/RunConfigurationPanel.cs
Labels: Area: Web Tools\ASP.NET Core

#8435 [release-8.3] LaunchSettings fix
  main/src/addins/AspNet/Projects/AspNetAppProjectFlavor.cs
  main/src/addins/MonoDevelop.AspNetCore/MonoDevelop.AspNetCore.Tests/MonoDevelop.AspNetCore.Tests/LaunchSettingsTests.cs
  main/src/addins/MonoDevelop.AspNetCore/MonoDevelop.AspNetCore/AspNetCoreExecutionHandler.cs
  main/src/addins/MonoDevelop.AspNetCore/MonoDevelop.AspNetCore/AspNetCoreProjectExtension.cs
  main/src/addins/MonoDevelop.AspNetCore/MonoDevelop.AspNetCore/AspNetCoreRunConfiguration.cs
  main/src/addins/MonoDevelop.AspNetCore/MonoDevelop.AspNetCore/AspNetCoreRunConfigurationEditor.cs
  main/src/addins/MonoDevelop.AspNetCore/MonoDevelop.AspNetCore/ILaunchProfile.cs
  main/src/addins/MonoDevelop.AspNetCore/MonoDevelop.AspNetCore/LaunchProfileData.cs
  main/src/addins/MonoDevelop.AspNetCore/MonoDevelop.AspNetCore/LaunchProfileProvider.cs
  main/src/core/MonoDevelop.Core/MonoDevelop.Projects/Project.cs
  main/src/core/MonoDevelop.Core/MonoDevelop.Projects/ProjectExtension.cs
  main/src/core/MonoDevelop.Core/MonoDevelop.Projects/ProjectFeature.cs
  main/src/core/MonoDevelop.Core/MonoDevelop.Projects/ProjectRunConfiguration.cs
  main/src/core/MonoDevelop.Core/MonoDevelop.Projects/SolutionItem.cs
  main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Projects.OptionPanels/RunConfigurationPanel.cs
Labels: Area: .NET Core

#8145 Move FileNesting operations on projects to NodeBuilder's
  main/src/addins/MonoDevelop.AspNetCore/MonoDevelop.AspNetCore.Tests/MonoDevelop.AspNetCore.Tests/AspNetCoreProjectTests.cs
  main/src/addins/MonoDevelop.AspNetCore/MonoDevelop.AspNetCore.Tests/MonoDevelop.AspNetCore.Tests/LaunchSettingsTests.cs
  main/src/addins/MonoDevelop.AspNetCore/MonoDevelop.AspNetCore.Tests/MonoDevelop.AspNetCore.Tests/PublishProfileTests.cs
  main/src/addins/MonoDevelop.AspNetCore/MonoDevelop.AspNetCore/AspNetCoreNestingRulesProvider.cs
  main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore.Tests/MonoDevelop.DotNetCore.Tests/DotNetCoreProjectTemplateTests.cs
  main/src/core/MonoDevelop.Core/MonoDevelop.Core.addin.xml
  main/src/core/MonoDevelop.Core/MonoDevelop.Core.csproj
  main/src/core/MonoDevelop.Core/MonoDevelop.Projects.FileNesting/FileNestingService.cs
  main/src/core/MonoDevelop.Core/MonoDevelop.Projects/ProjectFile.cs
  main/src/core/MonoDevelop.Ide/ExtensionModel/Commands.addin.xml
  main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Commands/ProjectCommands.cs
  main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Components/ExtensibleTreeView.cs
  main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Pads.ProjectPad/FolderNodeBuilder.cs
  main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Pads.ProjectPad/ProjectFileNodeBuilder.cs
  main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Pads.ProjectPad/ProjectNodeBuilder.cs
  main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Projects.FileNesting/FileNestingExtensionModel.addin.xml
  main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Projects.FileNesting/FileNestingService.cs
  main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Projects.FileNesting/NestingRule.cs
  main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Projects.FileNesting/NestingRulesProvider.cs
  main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.csproj
  main/tests/MonoDevelop.Core.Tests/MonoDevelop.Core.Tests.csproj
  main/tests/MonoDevelop.Core.Tests/MonoDevelop.Projects/FileNestingTests.cs
  main/tests/test-projects/aspnetcore-empty-30/aspnetcore-empty-30.sln
  main/tests/test-projects/aspnetcore-empty-30/aspnetcore-empty-30/Program.cs
  main/tests/test-projects/aspnetcore-empty-30/aspnetcore-empty-30/Properties/launchSettings.json
  main/tests/test-projects/aspnetcore-empty-30/aspnetcore-empty-30/Startup.cs
  main/tests/test-projects/aspnetcore-empty-30/aspnetcore-empty-30/appsettings.Development.json
  main/tests/test-projects/aspnetcore-empty-30/aspnetcore-empty-30/appsettings.json
  main/tests/test-projects/aspnetcore-empty-30/aspnetcore-empty-30/aspnetcore-empty-30.csproj
Labels: Area: .NET Core, Area: Project Model

#8498 [Mac] Send the correct frame
  main/src/addins/MacPlatform/MainToolbar/MainToolbar.cs
Labels: verified

#8397 [Debugger] Let VoiceOver read "Add breakpoint" and "Remove breakpoint"
  main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/DebugCommands.cs
Labels: verified

#8508 [release-8.3] [AutoTest] Add logging in NSObjectResult.SetActiveRuntime to trace source of NRE
  main/src/core/MonoDevelop.Ide/MonoDevelop.Components.AutoTest.Results/NSObjectResult.cs
Labels: Area: Infrastructure

#8495 [release-8.3] Move FileNesting operations on projects to NodeBuilder's
  main/src/addins/MonoDevelop.AspNetCore/MonoDevelop.AspNetCore.Tests/MonoDevelop.AspNetCore.Tests/AspNetCoreProjectTests.cs
  main/src/addins/MonoDevelop.AspNetCore/MonoDevelop.AspNetCore.Tests/MonoDevelop.AspNetCore.Tests/LaunchSettingsTests.cs
  main/src/addins/MonoDevelop.AspNetCore/MonoDevelop.AspNetCore.Tests/MonoDevelop.AspNetCore.Tests/PublishProfileTests.cs
  main/src/addins/MonoDevelop.AspNetCore/MonoDevelop.AspNetCore/AspNetCoreNestingRulesProvider.cs
  main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore.Tests/MonoDevelop.DotNetCore.Tests/DotNetCoreProjectTemplateTests.cs
  main/src/core/MonoDevelop.Core/MonoDevelop.Core.addin.xml
  main/src/core/MonoDevelop.Core/MonoDevelop.Core.csproj
  main/src/core/MonoDevelop.Core/MonoDevelop.Projects.FileNesting/FileNestingService.cs
  main/src/core/MonoDevelop.Core/MonoDevelop.Projects/ProjectFile.cs
  main/src/core/MonoDevelop.Ide/ExtensionModel/Commands.addin.xml
  main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Commands/ProjectCommands.cs
  main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Components/ExtensibleTreeView.cs
  main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Pads.ProjectPad/FolderNodeBuilder.cs
  main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Pads.ProjectPad/ProjectFileNodeBuilder.cs
  main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Pads.ProjectPad/ProjectNodeBuilder.cs
  main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Projects.FileNesting/FileNestingExtensionModel.addin.xml
  main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Projects.FileNesting/FileNestingService.cs
  main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Projects.FileNesting/NestingRule.cs
  main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Projects.FileNesting/NestingRulesProvider.cs
  main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.csproj
  main/tests/MonoDevelop.Core.Tests/MonoDevelop.Core.Tests.csproj
  main/tests/MonoDevelop.Core.Tests/MonoDevelop.Projects/FileNestingTests.cs
  main/tests/test-projects/aspnetcore-empty-30/aspnetcore-empty-30.sln
  main/tests/test-projects/aspnetcore-empty-30/aspnetcore-empty-30/Program.cs
  main/tests/test-projects/aspnetcore-empty-30/aspnetcore-empty-30/Properties/launchSettings.json
  main/tests/test-projects/aspnetcore-empty-30/aspnetcore-empty-30/Startup.cs
  main/tests/test-projects/aspnetcore-empty-30/aspnetcore-empty-30/appsettings.Development.json
  main/tests/test-projects/aspnetcore-empty-30/aspnetcore-empty-30/appsettings.json
  main/tests/test-projects/aspnetcore-empty-30/aspnetcore-empty-30/aspnetcore-empty-30.csproj
Labels: Area: .NET Core, Area: Web Tools\ASP.NET Core

#8544 Fixes 940776: System.ArgumentOutOfRangeException on selection change in drop down
  main/src/core/MonoDevelop.Ide/MonoDevelop.Components/DropDownBoxListWindow.cs
Labels: Area: VS Text Editor, do-not-merge

#7785 Adds feature to center current open panel based in parent window
  main/src/addins/MacPlatform/Dialogs/MacOpenFileDialogHandler.cs
  main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Extensions/IOpenFileDialogHandler.cs
  main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Dialogs/OpenFileDialog.cs
  main/src/core/MonoDevelop.Ide/MonoDevelop.Ide/MessageService.cs
Labels: Area: Shell

#8567 [Debugger] Fixed hang when showing the ExceptionCaughtDialog
  main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/ExceptionCaughtDialog.cs
Labels: verified

#8569 [Test Tools] let unit tests support "Show Test Source Code"
  main/src/addins/MonoDevelop.UnitTesting/MonoDevelop.UnitTesting.VsTest/VsTestTestClass.cs
  main/src/addins/MonoDevelop.UnitTesting/MonoDevelop.UnitTesting.VsTest/VsTestUnitTest.cs
Labels: verified

#8578 Bump Roslyn to 3.3.1-beta3-19426-02
  main/msbuild/RoslynVersion.props
Labels: Area: Roslyn Integration, Roslyn: Approved for merge

#8582 [release-8.3] Bump Roslyn to 3.3.1-beta3-19426-02
  main/msbuild/RoslynVersion.props
Labels: Area: Roslyn Integration

#8549 [release-8.3] Fixes VSTS Bug 972866: [Feedback] Preferences are not saved when I
  main/src/addins/MonoDevelop.Refactoring/MonoDevelop.Refactoring.Options/AbstractOptionPreviewViewModel.cs
  main/src/addins/MonoDevelop.Refactoring/MonoDevelop.Refactoring.Options/CheckBoxOptionViewModel.cs
  main/src/addins/MonoDevelop.Refactoring/MonoDevelop.Refactoring.Options/CheckBoxWithComboOptionViewModel.cs
  main/src/addins/MonoDevelop.Refactoring/MonoDevelop.Refactoring.Options/RadioButtonViewModel.cs
  main/src/addins/MonoDevelop.Refactoring/MonoDevelop.Refactoring.Options/Style/BooleanCodeStyleOptionViewModel.cs
  main/src/addins/MonoDevelop.Refactoring/MonoDevelop.Refactoring.Options/Style/EnumCodeStyleOptionViewModel.cs
Labels: verified
