Repository mono/monodevelop, pull requests merged in 2019-11, with the labels that each got.

#9193 [Debugger] Fixed deleting/changing of expressions in Watch Pad
  main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/ObjectValue/ExpressionEventArgs.cs
  main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/ObjectValue/ObjectValueTreeViewController.cs
  main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/WatchPad.cs
Labels: verified

#9216 Fixes 1007912: Keyboard focus isn't given to Solution pad
  main/src/core/MonoDevelop.Ide/MonoDevelop.Components/Mac/GtkNSViewHost.cs
Labels: Area: VS Text Editor, verified

#9227 [release-8.4] Fixes 1007912: Keyboard focus isn't given to Solution pad
  main/src/core/MonoDevelop.Ide/MonoDevelop.Components/Mac/GtkNSViewHost.cs
Labels: Area: VS Text Editor

#9218 Fix 988924: Some commands (save, undo) do not work if editor is detat…
  main/src/core/MonoDevelop.Ide/MonoDevelop.Components.Commands/CommandManager.cs
Labels: Area: VS Text Editor

#9219 [release-8.4] Fix 988924: Some commands (save, undo) do not work if editor is detat…
  main/src/core/MonoDevelop.Ide/MonoDevelop.Components.Commands/CommandManager.cs
Labels: Area: VS Text Editor

#9247 CommandManager: Add missing null check
  main/src/core/MonoDevelop.Ide/MonoDevelop.Components.Commands/CommandManager.cs
Labels: Area: VS Text Editor

#9252 [release-8.4] CommandManager: Add missing null check
  main/src/core/MonoDevelop.Ide/MonoDevelop.Components.Commands/CommandManager.cs
Labels: Area: VS Text Editor

#9151 Bump Roslyn to 3.4.0-beta3-19525-13
  main/msbuild/RoslynVersion.props
  main/src/core/Mono.TextEditor.Shared/Mono.TextEditor/Document/TextDocument.cs
  main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Documents/TextBufferFileModel.cs
Labels: Area: Roslyn Integration, Area: VS Text Editor, Roslyn: Approved for merge

#9154 [release-8.4] Bump Roslyn to 3.4.0-beta3-19525-13
  main/msbuild/RoslynVersion.props
  main/src/core/Mono.TextEditor.Shared/Mono.TextEditor/Document/TextDocument.cs
  main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Documents/TextBufferFileModel.cs
Labels: Area: Roslyn Integration, Area: VS Text Editor, Roslyn: Approved for merge

#9254 [release-8.4] Bump Roslyn to 3.4.0-beta4-19556-02
  main/msbuild/RoslynVersion.props
Labels: Area: Roslyn Integration, Area: VS Text Editor, Roslyn: Approved for merge

#9251 [Debugger] Fix UX glitches in the Locals & Watch pads
  main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/ObjectValue/Gtk/GtkObjectValueTreeView.cs
  main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/ObjectValue/Mac/MacDebuggerObjectNameView.cs
  main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/ObjectValue/Mac/MacDebuggerObjectValueView.cs
  main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.csproj
  main/src/core/MonoDevelop.Ide/icons/add-16~dark~sel.png
  main/src/core/MonoDevelop.Ide/icons/add-16~dark~sel@2x.png
  main/src/core/MonoDevelop.Ide/icons/add-16~sel.png
  main/src/core/MonoDevelop.Ide/icons/add-16~sel@2x.png
Labels: verified

#9271 [a11y] NuGet Package Management
  main/src/addins/MacPlatform/AccessibleGtkSearchEntryBackend.cs
  main/src/addins/MacPlatform/MacPlatform.cs
  main/src/addins/MacPlatform/MacPlatform.csproj
  main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement.Gui/AccessibleSpacerCellView.cs
  main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement.Gui/ManagePackagesCellView.cs
  main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement.Gui/ManagePackagesCellViewCheckBox.cs
  main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement.Gui/ManagePackagesDialog.UI.cs
  main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement.Gui/ManagePackagesDialog.cs
  main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement.csproj
Labels: verified

#9264 [AspNetCore] Don't hard code BuildAction for Razor Component template
  main/src/addins/MonoDevelop.AspNetCore/Templates/RazorComponent.xft.xml
Labels: Area: .NET Core

#9265 [release-8.4] [AspNetCore] Don't hard code BuildAction for Razor Component template
  main/src/addins/MonoDevelop.AspNetCore/Templates/RazorComponent.xft.xml
Labels: Area: .NET Core

#9238 [release-8.4] Fixes VSTS Bug 991658: Crashes from "Critical Gtk Errors" in log
  main/src/addins/MonoDevelop.AssemblyBrowser/MonoDevelop.AssemblyBrowser/AssemblyBrowserNavigationPoint.cs
  main/src/addins/MonoDevelop.AssemblyBrowser/MonoDevelop.AssemblyBrowser/AssemblyBrowserViewContent.cs
  main/src/addins/MonoDevelop.AssemblyBrowser/MonoDevelop.AssemblyBrowser/AssemblyBrowserWidget.cs
Labels: verified

#9270 [Debugger] Optimize debugger tooltip resizing
  main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger.VSTextView/PinnedWatches/PinnedWatchView.cs
  main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger.VSTextView/QuickInfo/MacDebuggerTooltipWindow.cs
  main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/ObjectValue/Mac/MacDebuggerObjectCellViewBase.cs
  main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/ObjectValue/Mac/MacDebuggerObjectNameView.cs
  main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/ObjectValue/Mac/MacDebuggerObjectTypeView.cs
  main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/ObjectValue/Mac/MacDebuggerObjectValueView.cs
  main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/ObjectValue/Mac/MacObjectValueNode.cs
  main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/ObjectValue/Mac/MacObjectValueTreeView.cs
  main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/ObjectValue/ShowMoreValuesObjectValueNode.cs
Labels: verified

#9276 Fixes drag and drop in toolbox when current event is IntPtr.Zero
  main/src/addins/MonoDevelop.DesignerSupport/MonoDevelop.DesignerSupport/ToolboxPad.cs
Labels: verified

#9275 Go to Definition for razor projection buffers
  main/src/addins/CSharpBinding/MonoDevelop.Ide.Completion.Presentation/MonoDevelopContainedDocument.cs
  main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.RoslynServices/MonoDevelopDocumentNavigationService.cs
  main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.TypeSystem/IMonoDevelopHostDocument.cs
Labels: Area: VS Text Editor

#9283 [release-8.4] Go to Definition for razor projection buffers
  main/src/addins/CSharpBinding/MonoDevelop.Ide.Completion.Presentation/MonoDevelopContainedDocument.cs
  main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.RoslynServices/MonoDevelopDocumentNavigationService.cs
  main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.TypeSystem/IMonoDevelopHostDocument.cs
Labels: Area: VS Text Editor

#9289 [release-8.4] Revert "Implement Go To Definition for Razor"
  main/src/addins/CSharpBinding/MonoDevelop.Ide.Completion.Presentation/MonoDevelopContainedDocument.cs
  main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.RoslynServices/MonoDevelopDocumentNavigationService.cs
  main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.TypeSystem/IMonoDevelopHostDocument.cs
Labels: Area: VS Text Editor

#9288 Revert "Implement Go To Definition for Razor"
  main/src/addins/CSharpBinding/MonoDevelop.Ide.Completion.Presentation/MonoDevelopContainedDocument.cs
  main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.RoslynServices/MonoDevelopDocumentNavigationService.cs
  main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.TypeSystem/IMonoDevelopHostDocument.cs
Labels: Area: VS Text Editor

#9291 [Debugger] Fix tooltips in razor and other projection buffers
  main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger.VSTextView/QuickInfo/DebuggerQuickInfoSource.cs
Labels: Area: Debugger, Area: VS Text Editor

#9292 [release-8.4] [Debugger] Fix tooltips in razor and other projection buffers
  main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger.VSTextView/QuickInfo/DebuggerQuickInfoSource.cs
Labels: Area: Debugger, Area: VS Text Editor

#9286 [Ide][Mac] Fix several focus contrast issues with Gtk
  main/src/core/MonoDevelop.Ide/gtkrc.mac
  main/src/core/MonoDevelop.Ide/gtkrc.mac-dark
Labels: verified

#9284 [Debugger] Simplify PinnedWatchView, allow scrolling children via popover
  main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger.VSTextView/PinnedWatches/PinnedWatchView.cs
  main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger.VSTextView/QuickInfo/MacDebuggerTooltipWindow.cs
  main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/ObjectValue/Mac/MacObjectValueTreeView.cs
  main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/ObjectValue/Mac/MacObjectValueTreeViewDataSource.cs
Labels: verified

#9307 Implement Go To Definition for Razor
  main/src/addins/CSharpBinding/MonoDevelop.Ide.Completion.Presentation/MonoDevelopContainedDocument.cs
  main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.RoslynServices/MonoDevelopDocumentNavigationService.cs
  main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.TypeSystem/IMonoDevelopHostDocument.cs
Labels: Area: VS Text Editor

#9308 [release-8.4] Implement Go To Definition for Razor
  main/src/addins/CSharpBinding/MonoDevelop.Ide.Completion.Presentation/MonoDevelopContainedDocument.cs
  main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.RoslynServices/MonoDevelopDocumentNavigationService.cs
  main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.TypeSystem/IMonoDevelopHostDocument.cs
Labels: Area: VS Text Editor

#9298 Refactor how virtual and dynamic documents are added to the workspace.
  main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.TypeSystem/DynamicFileManager.cs
  main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.TypeSystem/MonoDevelopWorkspace.ProjectSystemHandler.cs
  main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.TypeSystem/MonoDevelopWorkspace.cs
  main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.TypeSystem/TypeSystemService_WorkspaceHandling.cs
Labels: Area: VS Text Editor

#9311 [release-8.4] Refactor how virtual and dynamic documents are added to the workspace.
  main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.TypeSystem/DynamicFileManager.cs
  main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.TypeSystem/MonoDevelopWorkspace.ProjectSystemHandler.cs
  main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.TypeSystem/MonoDevelopWorkspace.cs
  main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.TypeSystem/TypeSystemService_WorkspaceHandling.cs
Labels: Area: VS Text Editor

#9325 Revert "First pass to fix solution pad not regaining focus on shortcut press."
  main/src/core/MonoDevelop.Ide/MonoDevelop.Components/Mac/GtkNSViewHost.cs
Labels: verified

#9315 [Debugger] Fixed calculation for NSTextField width as used by the tre…
  main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/ObjectValue/Mac/MacDebuggerObjectCellViewBase.cs
  main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/ObjectValue/Mac/MacDebuggerObjectNameView.cs
  main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/ObjectValue/Mac/MacDebuggerObjectValueView.cs
Labels: verified

#9324 Ensures don't close autohide window if focus are in embedded panels
  main/src/core/MonoDevelop.Ide/MonoDevelop.Components.Docking/DockBarItem.cs
Labels: verified

#9314 Instead of using custom ISerializable to serialize private fields, just expose it via ReadOnlyCollection
  main/src/core/MonoDevelop.Core/MonoDevelop.Core.Instrumentation/Counter.cs
  main/src/core/MonoDevelop.Core/MonoDevelop.Core.Instrumentation/TimerCounter.cs
  main/tests/MonoDevelop.Core.Tests/MonoDevelop.Core/InstrumentationTests.cs
Labels: Performance

#9343 Debugger: Fix pinned watches in .razor/.cshtml files
  main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger.VSTextView/PinnedWatches/PinnedWatchAdornmentManager.cs
Labels: Area: VS Text Editor

#9344 [release-8.4] Debugger: Fix pinned watches in .razor/.cshtml files
  main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger.VSTextView/PinnedWatches/PinnedWatchAdornmentManager.cs
Labels: Area: VS Text Editor

#9341 [release-8.4] Bump Roslyn to 3.4.0-beta4-19562-05
  main/msbuild/RoslynVersion.props
Labels: Area: Roslyn Integration, Area: VS Text Editor, Roslyn: Approved for merge

#9340 Bump Roslyn to 3.4.0-beta4-19562-05
  main/msbuild/RoslynVersion.props
Labels: Area: Roslyn Integration, Area: VS Text Editor, Roslyn: Approved for merge

#9361 Bump Roslyn to 3.4.0-beta4-19568-04
  main/msbuild/RoslynVersion.props
Labels: Area: Roslyn Integration, Area: VS Text Editor, Roslyn: Approved for merge

#9338 [Debugger] Fixed CanRename() logic for Locals/Watch context menu & al…
  main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/ObjectValue/Mac/MacObjectValueTreeView.cs
Labels: verified

#9371 [AspNet*] Add a group for ASP.NET Core Browser execution targets
  main/src/addins/AspNet/Projects/AspNetAppProjectFlavor.cs
  main/src/addins/MonoDevelop.AspNetCore/MonoDevelop.AspNetCore.Tests/MonoDevelop.AspNetCore.Tests/AspNetCoreProjectTests.cs
  main/src/addins/MonoDevelop.AspNetCore/MonoDevelop.AspNetCore/AspNetCoreProjectExtension.cs
  main/src/core/MonoDevelop.Core/MonoDevelop.Core.Execution/ExecutionTarget.cs
Labels: Area: Web Tools\ASP.NET Core

#9355 [Debugger] Incrementally load new children rather than remove-all and…
  main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/LocalsPad.cs
  main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/ObjectValue/Mac/MacObjectValueTreeView.cs
  main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/ObjectValue/Mac/MacObjectValueTreeViewDataSource.cs
  main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/ObjectValue/ObjectValueTreeViewController.cs
Labels: verified

#9166 [Debugger] Implemented code-completion for the new MacObjectValueTree…
  main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger.csproj
  main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/DebuggerAsyncCompletionSource.cs
  main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/DebuggerCompletionCommandHandler.cs
  main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/ObjectValue/Mac/MacDebuggerObjectNameView.cs
  main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/ObjectValue/Mac/MacDebuggerObjectTypeView.cs
  main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/ObjectValue/Mac/MacDebuggerTextField.cs
  main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/ObjectValue/Mac/MacObjectValueTreeView.cs
  main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/ObjectValue/ObjectValueTreeViewController.cs
Labels: verified

#9393 [Release-8.4] [Debugger] Implemented code-completion for the new MacObjectValueTree
  main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger.csproj
  main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/DebuggerAsyncCompletionSource.cs
  main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/DebuggerCompletionCommandHandler.cs
  main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/ObjectValue/Mac/MacDebuggerObjectNameView.cs
  main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/ObjectValue/Mac/MacDebuggerObjectTypeView.cs
  main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/ObjectValue/Mac/MacDebuggerTextField.cs
  main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/ObjectValue/Mac/MacObjectValueTreeView.cs
  main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/ObjectValue/ObjectValueTreeViewController.cs
Labels: verified
