Repository mono/monodevelop, pull requests merged in 2019-10, with the labels that each got.

#8843 [FileNesting] Remove debugging output from Ide.log
  main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Projects.FileNesting/NestingRule.cs
  main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Projects.FileNesting/NestingRulesProvider.cs
Labels: Area: .NET Core

#8502 [Toolbox][a11y] Some accessibility fixes
  main/src/addins/MonoDevelop.DesignerSupport/MonoDevelop.DesignerSupport.Toolbox/IToolboxWidget.cs
  main/src/addins/MonoDevelop.DesignerSupport/MonoDevelop.DesignerSupport.Toolbox/MacToolbox.cs
  main/src/addins/MonoDevelop.DesignerSupport/MonoDevelop.DesignerSupport.Toolbox/MacToolboxViewItems.cs
  main/src/addins/MonoDevelop.DesignerSupport/MonoDevelop.DesignerSupport.Toolbox/MacToolboxWidget.cs
  main/src/addins/MonoDevelop.DesignerSupport/MonoDevelop.DesignerSupport.Toolbox/MacToolboxWidgetFlowLayoutDelegate.cs
  main/src/addins/MonoDevelop.DesignerSupport/MonoDevelop.DesignerSupport.Toolbox/NativeViews/ClickedButton.cs
  main/src/addins/MonoDevelop.DesignerSupport/MonoDevelop.DesignerSupport.Toolbox/NativeViews/SearchTextField.cs
  main/src/addins/MonoDevelop.DesignerSupport/MonoDevelop.DesignerSupport.Toolbox/NativeViews/ToggleButton.cs
  main/src/core/MonoDevelop.Ide/MonoDevelop.Components/Mac/KeyCodes.cs
  main/src/core/MonoDevelop.Ide/MonoDevelop.Components/Mac/VerticalAlignmentTextCell.cs
  main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.csproj
Labels: Area: Shell, verified

#8867 Integrate inline diff previewer for lightbulb
  main/src/addins/MonoDevelop.SourceEditor2/Mono.TextEditor/Gui/MonoTextEditor.ITextView.cs
  main/src/addins/MonoDevelop.TextEditor/MonoDevelop.TextEditor.Cocoa/MonoDevelop.TextEditor.Cocoa.csproj
  main/src/addins/MonoDevelop.TextEditor/MonoDevelop.TextEditor.Cocoa/Properties/MonoDevelop.TextEditor.Cocoa.addin.xml
  main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Composition/PreviewFactoryService.cs
  main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.csproj
Labels: Area: VS Text Editor

#8874 Fix 997787 and Fix 992438
  main/src/addins/MonoDevelop.TextEditor/MonoDevelop.TextEditor.Cocoa/CocoaTextViewContent.cs
  main/src/core/MonoDevelop.Ide/MonoDevelop.Components/Mac/GtkNSViewHost.cs
Labels: Area: VS Text Editor

#8302 Enables by default propperty panel
  main/src/addins/MonoDevelop.DesignerSupport/MonoDevelop.DesignerSupport.Toolbox/Styles.cs
  main/src/addins/MonoDevelop.DesignerSupport/MonoDevelop.DesignerSupport.csproj
  main/src/addins/MonoDevelop.DesignerSupport/MonoDevelop.DesignerSupport/MacPropertyGrid.cs
  main/src/addins/MonoDevelop.DesignerSupport/MonoDevelop.DesignerSupport/MonoDevelopHostResourceProvider.cs
  main/src/addins/MonoDevelop.DesignerSupport/MonoDevelop.DesignerSupport/NativePropertyEditor/ComponentModelEditorProvider.cs
  main/src/addins/MonoDevelop.DesignerSupport/MonoDevelop.DesignerSupport/NativePropertyEditor/ComponentModelObjectEditor.cs
  main/src/addins/MonoDevelop.DesignerSupport/MonoDevelop.DesignerSupport/NativePropertyEditor/ComponentModelTarget.cs
  main/src/addins/MonoDevelop.DesignerSupport/MonoDevelop.DesignerSupport/NativePropertyEditor/PropertyDescriptorEventInfo.cs
  main/src/addins/MonoDevelop.DesignerSupport/MonoDevelop.DesignerSupport/NativePropertyEditor/PropertyInfo/DescriptorPropertyInfo.cs
  main/src/addins/MonoDevelop.DesignerSupport/MonoDevelop.DesignerSupport/NativePropertyEditor/PropertyInfo/DirectoryPathPropertyInfo.cs
  main/src/addins/MonoDevelop.DesignerSupport/MonoDevelop.DesignerSupport/NativePropertyEditor/PropertyInfo/EnumDescriptorPropertyInfo.cs
  main/src/addins/MonoDevelop.DesignerSupport/MonoDevelop.DesignerSupport/NativePropertyEditor/PropertyInfo/FilePathPropertyInfo.cs
  main/src/addins/MonoDevelop.DesignerSupport/MonoDevelop.DesignerSupport/NativePropertyEditor/PropertyInfo/FlagDescriptorPropertyInfo.cs
  main/src/addins/MonoDevelop.DesignerSupport/MonoDevelop.DesignerSupport/NativePropertyEditor/PropertyInfo/StringStandardValuesPropertyInfo.cs
  main/src/addins/MonoDevelop.DesignerSupport/MonoDevelop.DesignerSupport/NativePropertyEditors/PropertyPadEditorProvider.cs
  main/src/addins/MonoDevelop.DesignerSupport/MonoDevelop.DesignerSupport/NativePropertyEditors/PropertyPadItem.cs
  main/src/addins/MonoDevelop.DesignerSupport/MonoDevelop.DesignerSupport/NativePropertyEditors/PropertyPadObjectEditor.cs
  main/src/addins/MonoDevelop.DesignerSupport/MonoDevelop.DesignerSupport/PropertyPad.cs
Labels: Area: Shell, verified

#8869 Add support to Pack .net std lib projects
  main/src/addins/MonoDevelop.AspNetCore/Properties/MonoDevelop.AspNetCore.addin.xml
  main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore.Commands/PackCommandHandler.cs
  main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore.Tests/MonoDevelop.DotNetCore.Tests.csproj
  main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore.Tests/MonoDevelop.DotNetCore.Tests/PackProjectTests.cs
  main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore.csproj
  main/src/addins/MonoDevelop.DotNetCore/Properties/MonoDevelop.DotNetCore.addin.xml
  main/src/core/MonoDevelop.Core/MonoDevelop.Projects/Project.cs
  main/src/core/MonoDevelop.Core/MonoDevelop.Projects/ProjectService.cs
Labels: verified

#8882 Fix 824326: Shift+Enter not in new editor
  main/src/addins/MonoDevelop.TextEditor/MonoDevelop.TextEditor/EditorCommandHandlers.cs
  main/src/addins/MonoDevelop.TextEditor/MonoDevelop.TextEditor/Properties/MonoDevelop.TextEditor.addin.xml
Labels: Area: VS Text Editor

#8883 Don't allow Reset current property pad in case of item focused changed
  main/src/addins/MonoDevelop.DesignerSupport/MonoDevelop.DesignerSupport/PropertyPadVisitor.cs
Labels: verified

#8901 [release-8.4] [Debugger] Fixed the Placeholder text color when the row is selected/…
  main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/ObjectValue/Mac/MacDebuggerObjectNameView.cs
  main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/ObjectValue/Mac/MacDebuggerObjectValueView.cs
Labels: verified

#8899 [release-8.4] [Debugger] Let NSOutlineView take care of column resizing for us (exc…
  main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/ObjectValue/Mac/MacObjectValueTreeView.cs
  main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/ObjectValue/Mac/MacObjectValueTreeViewDelegate.cs
Labels: verified

#8895 [release-8.4] [Debugger] Use an actual spinner instead of a static image
  main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/ObjectValue/Mac/MacDebuggerObjectValueView.cs
Labels: verified

#8890 [release-8.4] [Debugger] Fixed the saving/restoring of watch expressions between se…
  main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/ObjectValuePad.cs
  main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/WatchPad.cs
Labels: verified

#8900 [Debugger] Fixed the Placeholder text color when the row is selected/…
  main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/ObjectValue/Mac/MacDebuggerObjectNameView.cs
  main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/ObjectValue/Mac/MacDebuggerObjectValueView.cs
Labels: verified

#8898 [Debugger] Let NSOutlineView take care of column resizing for us (exc…
  main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/ObjectValue/Mac/MacObjectValueTreeView.cs
  main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/ObjectValue/Mac/MacObjectValueTreeViewDelegate.cs
Labels: verified

#8889 [Debugger] Fixed the saving/restoring of watch expressions between se…
  main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/ObjectValuePad.cs
  main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/WatchPad.cs
Labels: verified

#8894 [Debugger] Use an actual spinner instead of a static image
  main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/ObjectValue/Mac/MacDebuggerObjectValueView.cs
Labels: verified

#8915 MiscellaneousFilesWorkspace: support .csx scripts
  main/src/addins/CSharpBinding/CSharpBinding.addin.xml
  main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.TypeSystem/MiscellaneousFilesWorkspace.cs
Labels: Area: C# Binding, Area: VS Text Editor

#8395 [IDE] [a11y] Rewrite new configuration dialog in Xwt
  main/src/core/MonoDevelop.Ide/Gui/MonoDevelop.Ide.Projects.NewConfigurationDialog.cs
  main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Dialogs/NewConfigurationDialog.cs
  main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Projects.OptionPanels/SolutionItemConfigurationsPanel.cs
  main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Projects/NewConfigurationDialog.cs
  main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.csproj
Labels: verified

#8891 [release-8.4] Fix 824326: Shift+Enter not in new editor
  main/src/addins/MonoDevelop.TextEditor/MonoDevelop.TextEditor/EditorCommandHandlers.cs
  main/src/addins/MonoDevelop.TextEditor/MonoDevelop.TextEditor/Properties/MonoDevelop.TextEditor.addin.xml
Labels: Area: VS Text Editor

#8938 Fix 1002331: Support "Focus Document" commands in new editor
  main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Commands/ViewCommands.cs
Labels: Area: VS Text Editor, verified

#8939 [release-8.4] Fix 1002331: Support "Focus Document" commands in new editor
  main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Commands/ViewCommands.cs
Labels: Area: VS Text Editor

#8931 [Debugger] Fixed the text color used when editing Locals/Watches
  main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/ObjectValue/Mac/MacDebuggerObjectNameView.cs
  main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/ObjectValue/Mac/MacDebuggerObjectValueView.cs
Labels: verified

#8923 [Catalina] Fixes broken accessory view in any NSSavePanel based panels (Cocoa bug)
  main/src/addins/MacPlatform/Dialogs/MacCommonFileDialogHandler.cs
Labels: verified

#8927 [release-8.4] [Catalina] Fixes broken accessory view in any NSSavePanel based panels (Cocoa bug)
  main/src/addins/MacPlatform/Dialogs/MacCommonFileDialogHandler.cs
Labels: verified

#8955 Fix leaktests
  main/src/addins/MonoDevelop.DesignerSupport/MonoDevelop.DesignerSupport/DesignerSupportService.cs
  main/src/addins/MonoDevelop.DesignerSupport/MonoDevelop.DesignerSupport/MacPropertyGrid.cs
  main/src/addins/MonoDevelop.DesignerSupport/MonoDevelop.DesignerSupport/NativePropertyEditor/ComponentModelEditorProvider.cs
  main/src/addins/MonoDevelop.DesignerSupport/MonoDevelop.DesignerSupport/NativePropertyEditor/ComponentModelObjectEditor.cs
Labels: verified

#8951 [release-8.4] [Ide] Fix document tabs container disposing widgets on mode change
  main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Shell/GtkShellDocumentViewContainerTabs.cs
Labels: verified

#8940 [release-8.4] Fixes VSTS Bug 937839: [Feedback] Text Editor: font weight ignored
  main/src/addins/MonoDevelop.Refactoring/MonoDevelop.Refactoring/RefactoringPreviewTooltipWindow.cs
  main/src/addins/MonoDevelop.SourceEditor2/Mono.TextEditor/Gui/CodePreviewWindow.cs
  main/src/addins/MonoDevelop.SourceEditor2/Mono.TextEditor/Gui/TextViewMargin.cs
  main/src/addins/MonoDevelop.SourceEditor2/MonoDevelop.SourceEditor/SourceEditorPrintOperation.cs
  main/src/core/Mono.TextEditor.Shared/Mono.TextEditor/TextEditorOptions.cs
  main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Editor/OSXEditor.cs
  main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Fonts/FontChooserPanelWidget.cs
  main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Fonts/FontService.cs
Labels: verified

#8935 Editor: Support for ShowQuickInfo command
  main/src/addins/MonoDevelop.TextEditor/MonoDevelop.TextEditor/Properties/MonoDevelop.TextEditor.addin.xml
Labels: Area: VS Text Editor

#8936 [release-8.4] Editor: Support for ShowQuickInfo command
  main/src/addins/MonoDevelop.TextEditor/MonoDevelop.TextEditor/Properties/MonoDevelop.TextEditor.addin.xml
Labels: Area: VS Text Editor

#8852 Fixes VSTS Bug 810343: Accessibility: Document View Tabs: Voice Over
  main/src/core/MonoDevelop.Ide/MonoDevelop.Components/Tabstrip.cs
Labels: verified

#8970 [Debugger] Use the ~sel icon variants when the row is selected
  main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/ObjectValue/Mac/MacDebuggerObjectCellViewBase.cs
  main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/ObjectValue/Mac/MacDebuggerObjectNameView.cs
  main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/ObjectValue/Mac/MacDebuggerObjectValueView.cs
Labels: verified

#8857 Bump Roslyn to 3.4.0-beta2-19476-01
  main/msbuild/RoslynVersion.props
  main/src/addins/CSharpBinding/CSharpBinding.csproj
  main/src/addins/CSharpBinding/MonoDevelop.CSharp.Refactoring/RefactoryCommands.cs
  main/src/addins/CSharpBinding/MonoDevelop.Ide.Completion.Presentation/IMyRoslynCompletionDataProvider.cs
  main/src/addins/CSharpBinding/MonoDevelop.Ide.Completion.Presentation/MyCSharpCompletionData.cs
  main/src/addins/CSharpBinding/MonoDevelop.Ide.Completion.Presentation/MyCSharpCompletionDataProvider.cs
  main/src/addins/CSharpBinding/MonoDevelop.Ide.Completion.Presentation/MyRoslynCompletionData.cs
  main/src/addins/CSharpBinding/MonoDevelop.Ide.Completion.Presentation/RoslynCommandTarget.cs
  main/src/addins/CSharpBinding/MonoDevelop.Ide.Completion.Presentation/RoslynCompletionPresenter.cs
  main/src/addins/CSharpBinding/MonoDevelop.Ide.Completion.Presentation/RoslynCompletionPresenterSession.ICompletionPresenterSession.cs
  main/src/addins/CSharpBinding/MonoDevelop.Ide.Completion.Presentation/RoslynCompletionPresenterSession.IIntelliSensePresenterSession.cs
  main/src/addins/CSharpBinding/MonoDevelop.Ide.Completion.Presentation/RoslynCompletionPresenterSession.View.cs
  main/src/addins/CSharpBinding/MonoDevelop.Ide.Completion.Presentation/RoslynExperimentationService.cs
  main/src/addins/MonoDevelop.Refactoring/MonoDevelop.Refactoring/StreamingFindUsagesPresenter.cs
  main/tests/MonoDevelop.CSharpBinding.Tests/MonoDevelop.CSharpBinding.Refactoring/CSharpCodeActionEditorExtensionTests.cs
Labels: Area: Roslyn Integration, Roslyn: Needs sign-off, do-not-merge

#8992 [release-8.4] Bump Roslyn to 3.4.0-beta2-19476-01
  main/msbuild/RoslynVersion.props
  main/src/addins/CSharpBinding/CSharpBinding.csproj
  main/src/addins/CSharpBinding/MonoDevelop.CSharp.Refactoring/RefactoryCommands.cs
  main/src/addins/CSharpBinding/MonoDevelop.Ide.Completion.Presentation/IMyRoslynCompletionDataProvider.cs
  main/src/addins/CSharpBinding/MonoDevelop.Ide.Completion.Presentation/MyCSharpCompletionData.cs
  main/src/addins/CSharpBinding/MonoDevelop.Ide.Completion.Presentation/MyCSharpCompletionDataProvider.cs
  main/src/addins/CSharpBinding/MonoDevelop.Ide.Completion.Presentation/MyRoslynCompletionData.cs
  main/src/addins/CSharpBinding/MonoDevelop.Ide.Completion.Presentation/RoslynCommandTarget.cs
  main/src/addins/CSharpBinding/MonoDevelop.Ide.Completion.Presentation/RoslynCompletionPresenter.cs
  main/src/addins/CSharpBinding/MonoDevelop.Ide.Completion.Presentation/RoslynCompletionPresenterSession.ICompletionPresenterSession.cs
  main/src/addins/CSharpBinding/MonoDevelop.Ide.Completion.Presentation/RoslynCompletionPresenterSession.IIntelliSensePresenterSession.cs
  main/src/addins/CSharpBinding/MonoDevelop.Ide.Completion.Presentation/RoslynCompletionPresenterSession.View.cs
  main/src/addins/CSharpBinding/MonoDevelop.Ide.Completion.Presentation/RoslynExperimentationService.cs
  main/src/addins/MonoDevelop.Refactoring/MonoDevelop.Refactoring/StreamingFindUsagesPresenter.cs
  main/tests/MonoDevelop.CSharpBinding.Tests/MonoDevelop.CSharpBinding.Refactoring/CSharpCodeActionEditorExtensionTests.cs
Labels: Area: Roslyn Integration, do-not-merge

#8971 [release-8.4] [Debugger] Use the ~sel icon variants when the row is selected
  main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/ObjectValue/Mac/MacDebuggerObjectCellViewBase.cs
  main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/ObjectValue/Mac/MacDebuggerObjectNameView.cs
  main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/ObjectValue/Mac/MacDebuggerObjectValueView.cs
Labels: verified

#8994 Bump Roslyn to 3.4.0-beta3-19518-02
  main/msbuild/RoslynVersion.props
  main/src/addins/CSharpBinding/MonoDevelop.CSharp.OptionProvider/StyleViewModel.cs
Labels: Area: Roslyn Integration, Roslyn: Approved for merge

#8997 [release-8.4] Bump Roslyn to 3.4.0-beta3-19518-02
  main/msbuild/RoslynVersion.props
  main/src/addins/CSharpBinding/MonoDevelop.CSharp.OptionProvider/StyleViewModel.cs
Labels: Area: Roslyn Integration, Area: VS Text Editor, Roslyn: Approved for merge, do-not-merge

#8914 Fixes pin tab separation on smaller tabs
  main/src/core/MonoDevelop.Ide/MonoDevelop.Components.DockNotebook/TabStrip.cs
Labels: verified

#8968 [release-8.4] [Debugger] Fixed tracking of current expressions in Watch Pad
  main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger.csproj
  main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/ObjectValue/ExpressionEventArgs.cs
  main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/ObjectValue/Mac/MacObjectValueTreeView.cs
  main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/ObjectValue/ObjectValueTreeViewController.cs
  main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/WatchPad.cs
Labels: verified

#8906 [Git] Azure DevOps Git Clone Hangs
  main/src/addins/VersionControl/MonoDevelop.VersionControl.Git/MonoDevelop.VersionControl.Git/GitCredentials.cs
  main/src/addins/VersionControl/MonoDevelop.VersionControl.Git/MonoDevelop.VersionControl.Git/GitRepository.cs
Labels: verified

#8943 Fixes VSTS Bug 1002571: Regression: VSC checkout message dialogs shown below progress dialog window.
  main/src/addins/MacPlatform/Dialogs/MacAlertDialogHandler.cs
  main/src/addins/VersionControl/MonoDevelop.VersionControl/MonoDevelop.VersionControl/CheckoutCommand.cs
  main/src/addins/VersionControl/MonoDevelop.VersionControl/MonoDevelop.VersionControl/VersionControlTask.cs
  main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.ProgressMonitoring/MessageDialogProgressMonitor.cs
  main/src/core/MonoDevelop.Ide/MonoDevelop.Ide/MessageService.cs
Labels: verified

#8958 [Debugger] Let Cocoa Do The Right Thing(tm)
  main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger.csproj
  main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/ObjectValue/Mac/MacDebuggerObjectCellViewBase.cs
  main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/ObjectValue/Mac/MacDebuggerObjectNameView.cs
  main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/ObjectValue/Mac/MacDebuggerObjectTypeView.cs
  main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/ObjectValue/Mac/MacDebuggerObjectValueView.cs
  main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/ObjectValue/Mac/MacDebuggerTextField.cs
  main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/ObjectValue/Mac/MacObjectValueTreeView.cs
Labels: verified

#8959 [release-8.4] [Debugger] Let Cocoa Do The Right Thing(tm)
  main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger.csproj
  main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/ObjectValue/Mac/MacDebuggerObjectCellViewBase.cs
  main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/ObjectValue/Mac/MacDebuggerObjectNameView.cs
  main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/ObjectValue/Mac/MacDebuggerObjectTypeView.cs
  main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/ObjectValue/Mac/MacDebuggerObjectValueView.cs
  main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/ObjectValue/Mac/MacDebuggerTextField.cs
  main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/ObjectValue/Mac/MacObjectValueTreeView.cs
Labels: verified

#9038 [AspNetCore] Avoid exception when saving run configurations
  main/src/addins/MonoDevelop.AspNetCore/MonoDevelop.AspNetCore/AspNetCoreProjectExtension.cs
Labels: Area: .NET Core

#9045 [release-8.4] Fix 959380: TextMate tagger does not work with extensions (VS compat issue)
  main/src/addins/MonoDevelop.TextEditor/MonoDevelop.TextEditor.Cocoa/TextMate/CustomRepositoryService.cs
  main/src/addins/MonoDevelop.TextEditor/MonoDevelop.TextEditor/Properties/MonoDevelop.TextEditor.addin.xml
  main/src/addins/MonoDevelop.TextEditor/MonoDevelop.TextEditor/RepositoryExtensionNode.cs
  main/src/addins/MonoDevelop.TextEditor/MonoDevelop.TextEditor/ThemeToClassification.cs
Labels: Area: VS Text Editor

#9039 [release-8.4] [AspNetCore] Avoid exception when saving run configurations
  main/src/addins/MonoDevelop.AspNetCore/MonoDevelop.AspNetCore/AspNetCoreProjectExtension.cs
Labels: Area: .NET Core

#9047 [DotNetCore] Fix detection of required runtime for the project being run
  main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore/DotNetCoreNotInstalledInfoBar.cs
  main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore/DotNetCoreProjectExtension.cs
  main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore/DotNetCoreRuntime.cs
Labels: Area: .NET Core

#9048 [Debugger] Move resize logout outside of core expandItem/collapseItem…
  main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/ObjectValue/Mac/MacObjectValueTreeView.cs
Labels: verified

#9069 [AspNetCore] Update ASP.NET Core file nesting rules
  main/src/addins/MonoDevelop.AspNetCore/MonoDevelop.AspNetCore.Tests/MonoDevelop.AspNetCore.Tests/AspNetCoreProjectTests.cs
  main/src/addins/MonoDevelop.AspNetCore/Resources/AspNetCore.filenesting.json
Labels: Area: .NET Core

#9092 [AspNetCore] Some launchSettings implementation code improvements
  main/src/addins/MonoDevelop.AspNetCore/MonoDevelop.AspNetCore/LaunchProfileProvider.cs
Labels: Area: .NET Core

#9101 [release-8.4] [AspNetCore] Some launchSettings implementation code improvements
  main/src/addins/MonoDevelop.AspNetCore/MonoDevelop.AspNetCore/LaunchProfileProvider.cs
Labels: Area: .NET Core

#9102 [DotNetCore] Allow selecting frameworks even if not installed
  main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore.Gui/DotNetCoreRuntimeOptionsPanelWidget.cs
  main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore.Tests/MonoDevelop.DotNetCore.Tests/DotNetCoreProjectTemplateTests.cs
  main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore/DotNetCoreProjectSupportedTargetFrameworks.cs
Labels: Area: .NET Core

#9106 [release-8.4] [DotNetCore] Allow selecting frameworks even if not installed
  main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore.Gui/DotNetCoreRuntimeOptionsPanelWidget.cs
  main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore.Tests/MonoDevelop.DotNetCore.Tests/DotNetCoreProjectTemplateTests.cs
  main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore/DotNetCoreProjectSupportedTargetFrameworks.cs
Labels: Area: .NET Core

#9090 [Debugger] Keep Watch Pad in sync with the Locals pad when user edits…
  main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/ObjectValue/ObjectValueTreeViewController.cs
  main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/WatchPad.cs
Labels: verified

#8944 [Ide] Hide .NET Runtimes selection behind feature switch
  main/src/core/MonoDevelop.Core/MonoDevelop.Core.Assemblies/MonoTargetRuntimeFactory.cs
  main/src/core/MonoDevelop.Ide/ExtensionModel/GlobalOptionsDialog.addin.xml
Labels: verified

#8731 [release-8.3] [AspNetCore] Fix Razor Class Lib file nesting test
  main/src/addins/MonoDevelop.AspNetCore/MonoDevelop.AspNetCore.Tests/MonoDevelop.AspNetCore.Tests/AspNetCoreProjectTests.cs
Labels: Area: .NET Core

#9133 [release-8.4] Fixes VSTS Bug 810293: Accessibility: Version Control - Changes:
  main/src/addins/VersionControl/MonoDevelop.VersionControl/MonoDevelop.VersionControl.Views/EditorCompareWidgetBase.DiffScrollbar.cs
  main/src/addins/VersionControl/MonoDevelop.VersionControl/MonoDevelop.VersionControl.Views/EditorCompareWidgetBase.MiddleArea.cs
  main/src/addins/VersionControl/MonoDevelop.VersionControl/MonoDevelop.VersionControl.Views/EditorCompareWidgetBase.cs
  main/src/addins/VersionControl/MonoDevelop.VersionControl/MonoDevelop.VersionControl.csproj
  main/src/core/MonoDevelop.Ide/MonoDevelop.Components.AtkCocoaHelper/AtkCocoaHelper.cs
  main/src/core/MonoDevelop.Ide/MonoDevelop.Components.AtkCocoaHelper/AtkCocoaHelperMac.cs
  main/src/core/MonoDevelop.Ide/MonoDevelop.Components.AtkCocoaHelper/AtkCocoaHelperNoOp.cs
Labels: verified

#9130 Include IndentationManagerImpl into VSMac
  main/src/addins/MonoDevelop.TextEditor/MonoDevelop.TextEditor.Cocoa/MonoDevelop.TextEditor.Cocoa.csproj
  main/src/addins/MonoDevelop.TextEditor/MonoDevelop.TextEditor.Cocoa/Properties/MonoDevelop.TextEditor.Cocoa.addin.xml
Labels: Area: VS Text Editor

#9126 [Debugger] Prevent pinned watches from disappearing during scroll/etc
  main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger.VSTextView/PinnedWatches/PinnedWatchAdornmentManager.cs
Labels: verified

#9134 [release-8.4] Include IndentationManagerImpl into VSMac
  main/src/addins/MonoDevelop.TextEditor/MonoDevelop.TextEditor.Cocoa/MonoDevelop.TextEditor.Cocoa.csproj
  main/src/addins/MonoDevelop.TextEditor/MonoDevelop.TextEditor.Cocoa/Properties/MonoDevelop.TextEditor.Cocoa.addin.xml
Labels: Area: VS Text Editor

#9131 Updated Visual Studio theme
  main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Editor.Highlighting/themes/VisualStudioStyle.json
Labels: verified

#8859 Fixes VSTS Bug 810301: Accessibility: Version Control - Author:
  main/src/addins/VersionControl/MonoDevelop.VersionControl/MonoDevelop.VersionControl.Views/BlameWidget.AuthorSectionAccessible.cs
  main/src/addins/VersionControl/MonoDevelop.VersionControl/MonoDevelop.VersionControl.Views/BlameWidget.cs
  main/src/addins/VersionControl/MonoDevelop.VersionControl/MonoDevelop.VersionControl.csproj
Labels: verified

#9096 [Ide] Unset some environment variables after they're no longer needed
  main/src/core/MonoDevelop.Core/MonoDevelop.Core/Gettext.cs
  main/src/core/MonoDevelop.Ide/MonoDevelop.Ide/IdeStartup.cs
Labels: verified

#9119 [release-8.4] Bump to .NET Core 3.1
  main/tests/test-projects/restore-netcore-offline/dotnetcoreconsole.csproj
Labels: Area: .NET Core

#8937 Abstracts IPropertyGrid and uses in Preferences to fix a11c issues
  main/external/fsharpbinding/MonoDevelop.FSharpBinding/FSharpFormattingPanelWidget.fs
  main/src/addins/MonoDevelop.DesignerSupport/MonoDevelop.DesignerSupport.Toolbox/MacToolbox.cs
  main/src/addins/MonoDevelop.DesignerSupport/MonoDevelop.DesignerSupport.Toolbox/NativeViews/SearchTextField.cs
  main/src/addins/MonoDevelop.DesignerSupport/MonoDevelop.DesignerSupport.Toolbox/NativeViews/ToggleButton.cs
  main/src/addins/MonoDevelop.DesignerSupport/MonoDevelop.DesignerSupport/IPropertyPad.cs
  main/src/addins/MonoDevelop.DesignerSupport/MonoDevelop.DesignerSupport/MacPropertyGrid.cs
  main/src/addins/MonoDevelop.DesignerSupport/MonoDevelop.DesignerSupport/NativePropertyEditor/ComponentModelEditorProvider.cs
  main/src/addins/MonoDevelop.DesignerSupport/MonoDevelop.DesignerSupport/NativePropertyEditor/ComponentModelObjectEditor.cs
  main/src/addins/MonoDevelop.DesignerSupport/MonoDevelop.DesignerSupport/NativePropertyEditor/PropertyInfo/DescriptorPropertyInfo.cs
  main/src/addins/MonoDevelop.DesignerSupport/MonoDevelop.DesignerSupport/PropertyPad.cs
  main/src/addins/Xml/Formatting/XmlFormattingPolicyPanelWidget.cs
  main/src/core/MonoDevelop.Ide/MonoDevelop.Components.Commands/CommandManager.cs
  main/src/core/MonoDevelop.Ide/MonoDevelop.Components.PropertyGrid/IPropertyGrid.cs
  main/src/core/MonoDevelop.Ide/MonoDevelop.Components.PropertyGrid/PropertyGrid.cs
  main/src/core/MonoDevelop.Ide/MonoDevelop.Components/Mac/GtkNSViewHost.cs
  main/src/core/MonoDevelop.Ide/MonoDevelop.Components/Mac/NativeViewHelper.cs
  main/src/core/MonoDevelop.Ide/MonoDevelop.Ide/MessageService.cs
Labels: verified

#9117 Bump to .NET Core 3.1
  main/tests/test-projects/restore-netcore-offline/dotnetcoreconsole.csproj
Labels: Area: .NET Core, do-not-merge

#9161 [Debugger] Add line/filename to toggle breakpoint voice over message
  main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/DebugCommands.cs
Labels: verified

#9178 [master] Set `DesignTimeBuild` when evaluating SourceFiles
  main/src/core/MonoDevelop.Core/MonoDevelop.Projects/Project.cs
Labels: Area: VS Text Editor
